In [1]:
import pandas as pd
import numpy as np
import warnings
import re
import matplotlib.pyplot as plt
import scienceplots
plt.style.use(['science', 'notebook', 'grid'])
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag
from nltk.corpus import wordnet
import ast

import copy
from collections import Counter
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('sonas.csv', sep=',', encoding='UTF-8')
df.insert(loc=4, column='full_text_clean', value=df['Full Text'])

df['full_text_clean'] = df['full_text_clean'].str.replace(r'\n', ' ', regex=True)  # Remove newlines
df['full_text_clean'] = df['full_text_clean'].str.lower()  # Convert to lowercase
df['full_text_clean'] = df['full_text_clean'].str.replace(r'[^\w\s]+', ' ', regex=True)  # Remove punctuation
df['full_text_clean'] = df['full_text_clean'].str.replace(r'[0-9]+', '', regex=True)  # Remove numbers
df['full_text_clean'] = df['full_text_clean'].str.replace(r' +', ' ', regex=True).str.strip()  # Remove extra spaces
df['full_text_clean'] = df['full_text_clean'].apply(word_tokenize) # Apply tokenization

stop_words = set(stopwords.words('english'))
df['full_text_clean'] = df['full_text_clean'].apply(lambda x: [word for word in x if word not in stop_words])

df

,Title,Month,Year,Full Text,full_text_clean
0,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[dear, members, parliament, congratulations, o..."
1,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[dear, compatriots, distinguished, members, pa..."
2,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[president, kassym, jomart, tokayev, state, na..."
3,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[new, kazakhstan, path, renewal, modernisation..."
4,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, people, systemic, reforms, solid, foun..."
5,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[kazakhstan, new, reality, time, action, work,..."
6,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[president, kassym, jomart, tokayev, state, na..."
7,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[growing, welfare, kazakh, citizens, increase,..."
8,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[new, opportunities, fourth, industrial, revol..."
9,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[third, modernization, kazakhstan, global, com..."
10,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[kazakhstan, way, common, aim, common, interes..."
11,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[address, president, republic, kazakhstan, lea..."
12,Address by the President of the Republic of Ka...,December,2012,al and professional growth. The state and the ...,"[al, professional, growth, state, people, unde..."
13,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[address, president, republic, kazakhstan, nur..."
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, together, address, presiden..."
15,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[new, decade, new, economic, upswing, new, opp..."
16,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, dear, compatrio..."
17,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[address, president, republic, kazakhstan, h, ..."
18,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[new, kazakhstan, new, world, dear, deputies, ..."
19,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[kazakhstan, strategy, joining, world, competi..."
20,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[kazakhstan, road, accelerated, economic, soci..."
21,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, year, added, confidence, optimism, term..."
22,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, continues, develop, successfully, ac..."
23,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[main, directions, domestic, foreign, policy, ..."
24,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, main, directions, domesti..."
25,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[towards, free, effective, secure, society, de..."
26,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, countries, new, century,..."
27,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, directions, domest..."
28,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, ever, growing, welfare,..."

In [3]:
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN 

l = WordNetLemmatizer()
df['full_text_clean'] = df['full_text_clean'].apply(
    lambda tokens: [
        l.lemmatize(word, get_wordnet_pos(pos_tag([word])[0][1]))
        for word in tokens
    ]
)
#df['full_text_clean'] = df['tokens'].apply(lambda x: ' '.join(x))

df

,Title,Month,Year,Full Text,full_text_clean
0,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[dear, member, parliament, congratulation, ope..."
1,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[dear, compatriot, distinguish, member, parlia..."
2,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[president, kassym, jomart, tokayev, state, na..."
3,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[new, kazakhstan, path, renewal, modernisation..."
4,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, people, systemic, reform, solid, found..."
5,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[kazakhstan, new, reality, time, action, work,..."
6,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[president, kassym, jomart, tokayev, state, na..."
7,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, kazakh, citizen, increase, inc..."
8,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[new, opportunity, fourth, industrial, revolut..."
9,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[third, modernization, kazakhstan, global, com..."
10,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[kazakhstan, way, common, aim, common, interes..."
11,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[address, president, republic, kazakhstan, lea..."
12,Address by the President of the Republic of Ka...,December,2012,al and professional growth. The state and the ...,"[al, professional, growth, state, people, unde..."
13,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[address, president, republic, kazakhstan, nur..."
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, together, address, presiden..."
15,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[new, decade, new, economic, upswing, new, opp..."
16,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, dear, compatrio..."
17,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[address, president, republic, kazakhstan, h, ..."
18,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[new, kazakhstan, new, world, dear, deputy, me..."
19,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[kazakhstan, strategy, join, world, competitiv..."
20,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[kazakhstan, road, accelerate, economic, socia..."
21,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, year, add, confidence, optimism, term, ..."
22,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, continue, develop, successfully, acc..."
23,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[main, direction, domestic, foreign, policy, d..."
24,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, main, direction, domestic..."
25,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[towards, free, effective, secure, society, de..."
26,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, new, century, d..."
27,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti..."
28,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, ever, grow, welfare, ka..."

In [4]:
import copy
df_test = copy.deepcopy(df)
df_test.head()

,Title,Month,Year,Full Text,full_text_clean
0,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[dear, member, parliament, congratulation, ope..."
1,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[dear, compatriot, distinguish, member, parlia..."
2,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[president, kassym, jomart, tokayev, state, na..."
3,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[new, kazakhstan, path, renewal, modernisation..."
4,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, people, systemic, reform, solid, found..."

In [5]:
total_word_count_before = df_test['Full Text'].str.replace('\n', ' ', regex=False).str.split().explode().count()

print("Total word count:", total_word_count_before)

Total word count: 218669

In [6]:
custom_stop = ["law", "new", "pay", "way", "key", "let", "u", "use", "aim", "one", "set", "may", "yet", "ten", "two", "non", "raw", 
"km", "per", "end", "npp", "air", "ust", "top", "e", "lay", "sea", "ton", "bad", "go", 
"put", "mp", "pre", "led", "say", "act", "ass", "age", "die", "day", "men", "son", 
"lie", "sow", "un", "see", "lot", "era", "met", "gdp", "hit", "wto", "low", "arm", 
"esg", "le", "dry", "xi", "due", "fit", "sum", "ipo", "net", "ask", "vat", "ups", 
"red", "de", "tap", "man", "pas", "th", "fee", "car", "fix", "get", "rid", "ppp", 
"sez", "co", "map", "el", "eye", "hr", "yes", "mid", "run", "far", "war", "fun", 
"ban", "apk", "ago", "ngo", "fur", "saw", "bet", "і", "cut", "usd", "ii", "ill", 
"iii", "tve", "iv", "mw", "v", "vi", "vii", "six", "art", "ci", "sit", "nur", "win", 
"bid", "sme", "ivf", "gap", "big", "bed", "lag", "apo", "al", "got", "ho", "jet", 
"eco", "g", "dog", "hot", "mci", "etc", "c", "bar", "phc", "usa", "st", "eu", 
"tie", "yel", "boy", "re", "kwh", "күй", "bio", "b", "kzt", "nd", "rd", "jac", "sco", "jsc", 
"sub", "eve", "nce", "n", "fdi", "via", "box", "ore", "r", "arc", "oic", "bit", "god", 
"bug", "buy", "ce", "ski", "phd", "hiv", "row", "cec", "xxi", "pit", "tpp", "hpp", 
"pdp", "jvc", "pin", "joy", "aul", "h", "mr", "cum", "sec", "ad", "hoc", "us","pro",
"con", "spk", "sbc", "hei", "mix", "tv", "add", "try", "iso", "id", "opt", "geo", 
"bn", "mln", "pc", "luc", "xx", "kg", "tc", "xvi", "jew", "sag", "dy", "rob", "quo", 
"fed", "sun", "eat", "prc", "uno", "imf", "lax", "bi", "jts", "leg", "dug", "min", "fax", "w", "tg", "cpc", "bin", "bud"]

other_stop = [
    "kazakhstan", "ofkazakhstan", "year", "must", "need", "also", "first", "become", "would", "term",
    "right", "therefore", "high", "take", "many", "make", "kazakh", "however", "based",
    "second", "strengthening", "astana", "full", "kazakhstani", "achieve", "especially",
    "thousand", "kassym", "jomart", "tokayev", "nazarbayev", "nursultan", "establish", "even",
    "creating", "professional", "training", "give", "mean", "like stage", "percent",
    "significant", "among", "whole", "come", "taking", "ensuring", "fully", "example", "able",
    "general", "additional", "always", "following", "reduce", "improving", "working", "fourth",
    "five", "another", "cent", "still", "done", "move", "january", "decade", "code", "secondly",
    "sized", "living", "least", "thus", "appropriate", "paid", "remains", "amount", "almaty", "thing",
    "firstly", "question", "existing", "total", "republic", "around", "every", "long", "within",
    "already", "basis", "without", "three","good", "body", "address", "jumystyń", "kózin", "baılyqtyń", "ózin", 
    "besіgindi", "besіgі", "ғаламтор", "қолтырауын", "сандық", "otherы", "besіgі",
    "system", "well", "next", "part", "together", "third", "last", "made", 
    "towards", "serious", "since", "could", "much", "almost", "ever", "never", "along", "everything",
    "shall", "trillion", "thirdly", "particular", "regard", "provided", "meet", "given", "taken", "dear", "member",
    "compatriot", "congratulation", "parliament", "create", "like", "self", "various", "different", "needed", "essential",
    "requires", "clearly", "bring", "used", "fifth", "think", "require", "involved", "making", "said","main", "task", "continue",
    "work", "tenge", "necessary", "important", "aimed", "actively", "consider", "know", "single","responsible",
    "propose", "half", "include", "concrete", "greater", "carried", "show", "capable", "matter", "highly", "others", "solving",
    "turn", "currently", "word", "primarily", "type", "foremost", "related", "attention", "view", "time", "people",
    "sixth", "quite", "finally", "particularly", "president", "fact", "form"
]

In [7]:
df_test['full_text_clean'] = df_test['full_text_clean'].apply(
    lambda tokens: [word for word in tokens if word not in custom_stop and word not in other_stop]
)

In [8]:
df_test

,Title,Month,Year,Full Text,full_text_clean
0,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[opening, regular, session, wish, success, act..."
1,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[distinguish, government, accordance, article,..."
2,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[state, nation, fair, state, nation, prosperou..."
3,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[path, renewal, modernisation, friend, today, ..."
4,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, systemic, reform, solid, foundation, n..."
5,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[reality, action, session, begin, challenge, c..."
6,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[state, nation, constructive, public, dialogue..."
7,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, citizen, increase, income, qua..."
8,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[opportunity, industrial, revolution, today, w..."
9,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[modernization, global, competitiveness, appro..."
10,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[common, common, interest, common, future, fel..."
11,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[leader, nation, strategy, political, course, ..."
12,Address by the President of the Republic of Ka...,December,2012,al and professional growth. The state and the ...,"[growth, state, understand, instill, patriotis..."
13,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[socio, economic, modernization, vector, devel..."
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, deputy, government, lady, g..."
15,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[economic, upswing, opportunity, difficult, pe..."
16,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, today, world, d..."
17,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[growth, welfare, citizen, primary, goal, stat..."
18,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[world, deputy, government, lady, gentleman, i..."
19,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[strategy, join, world, competitive, country, ..."
20,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[road, accelerate, economic, social, political..."
21,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, confidence, optimism, national, economi..."
22,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, develop, successfully, accordance, s..."
23,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[direction, domestic, foreign, policy, deputy,..."
24,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, direction, domestic, fore..."
25,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[free, effective, secure, society, date, histo..."
26,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, century, genera..."
27,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti..."
28,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, grow, welfare, message,..."

In [9]:
df_test.sort_values(by=['Year', 'Month'], inplace=True)
df_test.reset_index(drop=True, inplace=True)

In [10]:
df_test

,Title,Month,Year,Full Text,full_text_clean
0,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, grow, welfare, message,..."
1,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti..."
2,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, century, genera..."
3,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[free, effective, secure, society, date, histo..."
4,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, direction, domestic, fore..."
5,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[direction, domestic, foreign, policy, deputy,..."
6,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, develop, successfully, accordance, s..."
7,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, confidence, optimism, national, economi..."
8,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[road, accelerate, economic, social, political..."
9,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[strategy, join, world, competitive, country, ..."
10,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[world, deputy, government, lady, gentleman, i..."
11,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[growth, welfare, citizen, primary, goal, stat..."
12,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, today, world, d..."
13,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[economic, upswing, opportunity, difficult, pe..."
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, deputy, government, lady, g..."
15,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[leader, nation, strategy, political, course, ..."
16,Address by the President of the Republic of Ka...,December,2012,al and professional growth. The state and the ...,"[growth, state, understand, instill, patriotis..."
17,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[socio, economic, modernization, vector, devel..."
18,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[common, common, interest, common, future, fel..."
19,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[modernization, global, competitiveness, appro..."
20,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[opportunity, industrial, revolution, today, w..."
21,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, citizen, increase, income, qua..."
22,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[state, nation, constructive, public, dialogue..."
23,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[reality, action, session, begin, challenge, c..."
24,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, systemic, reform, solid, foundation, n..."
25,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[path, renewal, modernisation, friend, today, ..."
26,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[state, nation, fair, state, nation, prosperou..."
27,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[distinguish, government, accordance, article,..."
28,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[opening, regular, session, wish, success, act..."

In [11]:
all_tokens = [token for sublist in df_test["full_text_clean"] for token in sublist]
token_counts = Counter(all_tokens)
top_500 = token_counts.most_common(500)
top_500_df = pd.DataFrame(top_500, columns=["token", "count"])

In [12]:
top_500_df.to_csv("top_500_df_V2.csv", index=False)

In [13]:
df_test.columns

Index(['Title', 'Month', 'Year', 'Full Text', 'full_text_clean'], dtype='object')

In [14]:
sentences = list(df_test['full_text_clean'])
sentences

[['prosperity',
  'security',
  'grow',
  'welfare',
  'message',
  'country',
  'century',
  'virgil',
  'epoch',
  'goal',
  'heine',
  'introduction',
  'nothing',
  'remote',
  'yesterday',
  'nothing',
  'close',
  'tomorrow',
  'folk',
  'proverb',
  'fellow',
  'citizen',
  'appeal',
  'share',
  'vision',
  'future',
  'society',
  'mission',
  'state',
  'want',
  'present',
  'strategy',
  'sure',
  'help',
  'gain',
  'future',
  'accomplish',
  'mission',
  'wish',
  'share',
  'consideration',
  'future',
  'loom',
  'ahead',
  'century',
  'millenium',
  'pretty',
  'remote',
  'perspective',
  'future',
  'want',
  'build',
  'child',
  'believe',
  'ripen',
  'profound',
  'awareness',
  'longer',
  'live',
  'merely',
  'incessant',
  'turmoil',
  'settle',
  'present',
  'clear',
  'knowledge',
  'understand',
  'construct',
  'trajectory',
  'highway',
  'development',
  'ensure',
  'game',
  'objetives',
  'correct',
  'identification',
  'priority',
  'choose',
  'relevant',
  'strategy',
  'manifest',
  'firm',
  'persistence',
  'follow',
  'path',
  'dispense',
  'unnecessary',
  'track',
  'waste',
  'energy',
  'resource',
  'provide',
  'strategy',
  'firmness',
  'purpose',
  'accomplish',
  'goal',
  'overcome',
  'obstacle',
  'block',
  'hard',
  'condition',
  'tackle',
  'today',
  'deprive',
  'hope',
  'enthusiasm',
  'clear',
  'awareness',
  'prospect',
  'honest',
  'presentation',
  'eventual',
  'difficulty',
  'privation',
  'empeding',
  'help',
  'mobilize',
  'effort',
  'citizen',
  'society',
  'settle',
  'common',
  'remeber',
  'apart',
  'goal',
  'period',
  'today',
  'generation',
  'bear',
  'tremendous',
  'responsibility',
  'future',
  'generation',
  'responsibility',
  'parent',
  'grandparent',
  'child',
  'grandchild',
  'child',
  'grandchild',
  'want',
  'remote',
  'future',
  'healthy',
  'educate',
  'live',
  'prosperous',
  'democratic',
  'society',
  'live',
  'peace',
  'feel',
  'safe',
  'safe',
  'child',
  'feel',
  'safe',
  'walk',
  'street',
  'feel',
  'safe',
  'property',
  'indeed',
  'succeed',
  'strong',
  'state',
  'friendly',
  'relation',
  'neighbour',
  'whether',
  'remote',
  'close',
  'today',
  'answer',
  'seemingly',
  'simple',
  'pretty',
  'wisdom',
  'remark',
  'reach',
  'goal',
  'follow',
  'path',
  'mind',
  'clear',
  'vision',
  'model',
  'future',
  'present',
  'generally',
  'specific',
  'short',
  'objective',
  'wherefore',
  'action',
  'permanently',
  'stick',
  'certain',
  'standard',
  'verify',
  'follow',
  'whether',
  'progress',
  'track',
  'whether',
  'outstrip',
  'development',
  'behind',
  'mentally',
  'contrast',
  'passing',
  'process',
  'repeat',
  'somewhat',
  'perception',
  'scope',
  'import',
  'problem',
  'ahead',
  'feel',
  'world',
  'planet',
  'large',
  'help',
  'feel',
  'nag',
  'breath',
  'epoch',
  'draw',
  'near',
  'state',
  'emerge',
  'world',
  'epoch',
  'powerful',
  'empire',
  'ottoman',
  'austrian',
  'hungarian',
  'recently',
  'soviet',
  'union',
  'today',
  'building',
  'state',
  'market',
  'economy',
  'democracy',
  'independent',
  'state',
  'trodden',
  'path',
  'similar',
  'enough',
  'today',
  'live',
  'epoch',
  'grow',
  'globalization',
  'close',
  'interrelationship',
  'powerful',
  'outer',
  'force',
  'inevitably',
  'play',
  'pretty',
  'substantial',
  'role',
  'determine',
  'future',
  'clever',
  'enough',
  'intention',
  'honest',
  'analysis',
  'external',
  'internal',
  'factor',
  'development',
  'chance',
  'choose',
  'identify',
  'priority',
  'elaborate',
  'relevant',
  'strategy',
  'consolidation',
  'history',
  'unique',
  'circumstance',
  'sure',
  'enough',
  'ought',
  'study',
  'experience',
  'country',
  'advantage',
  'auspicious',
  'tendency',
  'world',
  'community',
  'none',
  'cop',
  'enormous',
  'indispensable',
  'implementation',
  'dream',
  'hope',
  'building',
  'child',
  'grandchild',
  'proud',
  'today',
  'ready',
  'yesterday',
  'short',
  'experience',
  'knowledge',
  'hardly',
  'afford',
  'unfavourable',
  'circumstance',
  'sort',
  'instability',
  'essence',
  'precede',
  'period',
  'consist',
  'eventual',
  'survival',
  'independent',
  'state',
  'stormy',
  'condition',
  'budding',
  'transition',
  'period',
  'prognosticate',
  'sheer',
  'failure',
  'cope',
  'unprecedentedly',
  'tremendous',
  'building',
  'state',
  'social',
  'economic',
  'transformation',
  'collapse',
  'altogether',
  'today',
  'clear',
  'withstood',
  'trial',
  'fly',
  'colour',
  'alive',
  'kick',
  'notwithstanding',
  'obstacle',
  'safely',
  'emerge',
  'abyss',
  'chaos',
  'disorder',
  'present',
  'stage',
  'stabilization',
  'successfully',
  'settle',
  'urgent',
  'paramount',
  'problem',
  'chance',
  'retrospective',
  'analysis',
  'trustworthy',
  'evaluation',
  'pass',
  'afford',
  'face',
  'future',
  'contemplate',
  'perspective',
  'development',
  'elaborate',
  'plan',
  'experience',
  'statehood',
  'implement',
  'political',
  'economic',
  'reform',
  'knowledge',
  'world',
  'govern',
  'tolerance',
  'understand',
  'gain',
  'arduous',
  'condition',
  'strong',
  'confident',
  'frankly',
  'speak',
  'afford',
  'solution',
  'tomorrow',
  'afford',
  'wait',
  'completion',
  'reform',
  'early',
  'yesterday',
  'might',
  'late',
  'tomorrow',
  'strategic',
  'plan',
  'summons',
  'effort',
  'discipline',
  'enhances',
  'activity',
  'plan',
  'concentrate',
  'state',
  'pretty',
  'narrow',
  'range',
  'priority',
  'urge',
  'government',
  'daily',
  'settle',
  'strategy',
  'enhances',
  'daily',
  'annual',
  'activity',
  'score',
  'goal',
  'enough',
  'guideline',
  'practice',
  'realize',
  'plan',
  'contemplate',
  'utterly',
  'indispensable',
  'ministry',
  'department',
  'organize',
  'month',
  'nearer',
  'objective',
  'public',
  'servant',
  'awareness',
  'strategic',
  'goal',
  'priority',
  'settle',
  'waste',
  'meddling',
  'minor',
  'daily',
  'chore',
  'decision',
  'adopt',
  'correlate',
  'strategy',
  'whereas',
  'proper',
  'concentrate',
  'purposeful',
  'onwards',
  'annual',
  'plan',
  'priority',
  'monitoring',
  'answer',
  'advanced',
  'gain',
  'objective',
  'strategic',
  'planning',
  'strategic',
  'control',
  'accountability',
  'responsibility',
  'prerequisite',
  'sustainable',
  'steady',
  'progress',
  'consolidation',
  'society',
  'goal',
  'unity',
  'walk',
  'group',
  'population',
  'strategy',
  'settle',
  'common',
  'problem',
  'feasible',
  'duly',
  'consideration',
  'society',
  'group',
  'population',
  'identify',
  'relevant',
  'priority',
  'ensure',
  'realization',
  'thereof',
  'do',
  'atmosphere',
  'cooperation',
  'state',
  'group',
  'population',
  'private',
  'sector',
  'message',
  'elaborate',
  'framework',
  'constitutional',
  'duty',
  'annually',
  'concern',
  'basic',
  'trend',
  'domestic',
  'foreign',
  'policy',
  'mention',
  'state',
  'society',
  'large',
  'global',
  'vision',
  'strategy',
  'guide',
  'coordinate',
  'enable',
  'draw',
  'annual',
  'plan',
  'action',
  'issue',
  'consideration',
  'message',
  'subsequent',
  'annual',
  'message',
  'devote',
  'major',
  'trend',
  'domestic',
  'foreign',
  'policy',
  'contain',
  'evaluation',
  'implementation',
  'strategy',
  'identify',
  'specific',
  'objective',
  'whereabouts',
  'today',
  'occurs',
  'moment',
  'tide',
  'life',
  'brings',
  'luck',
  'avail',
  'miss',
  'happen',
  'follow',
  'shallow',
  'water',
  'disaster',
  'shakespeare',
  'bright',
  'opportunity',
  'suspect',
  'encounter',
  'dun',
  'late',
  'involve',
  'pursue',
  'major',
  'strategic',
  'goal',
  'sovereign',
  'independent',
  'state',
  'today',
  'grant',
  'remember',
  'fairly',
  'rare',
  'occurrence',
  'history',
  'embark',
  'implement',
  'broad',
  'scale',
  'social',
  'political',
  'economic',
  'transformation',
  'goal',
  'score',
  'though',
  'area',
  'manifest',
  'tangible',
  'result',
  'situation',
  'profound',
  'consideration',
  'analyse',
  'development',
  'point',
  'world',
  'expertise',
  'consequently',
  'compare',
  'progress',
  'transformation',
  'institution',
  'best',
  'world',
  'experience',
  'analyse',
  'advantage',
  'flaw',
  'serve',
  'indispensable',
  'prelude',
  'elaborate',
  'strategy',
  'start',
  'analyse',
  'domestic',
  'advantage',
  'external',
  'opportunity',
  'enjoys',
  'weak',
  'point',
  'trouble',
  'anticipate',
  'country',
  'proud',
  'eight',
  'advantage',
  'laid',
  'foundation',
  'independent',
  'sovereign',
  'state',
  'requisite',
  'state',
  'institution',
  'passing',
  'month',
  'brings',
  'great',
  'experience',
  'knowledge',
  'development',
  'state',
  'completion',
  'former',
  'political',
  'economic',
  'seventy',
  'dominate',
  'life',
  'today',
  'altogether',
  'state',
  'utterly',
  'political',
  'economic',
  'influence',
  'transformation',
  'unfold',
  'society',
  'though',
  'wholly',
  'unawares',
  'change',
  'dramatically',
  'qualitatively',
  'value',
  'altogether',
  'standard',
  'human',
  'relation',
  'short',
  'free',
  'state',
  'collective',
  'world',
  'outlook',
  'replace',
  'private',
  'individual',
  'event',
  'reverse',
  'aspect',
  'life',
  'sure',
  'enough',
  'discard',
  'offer',
  'secure',
  'minimum',
  'social',
  'benefit',
  'success',
  'number',
  'field',
  'remember',
  'fell',
  'apart',
  'prove',
  'noncompetitive',
  'economic',
  'point',
  'obviously',
  'fail',
  'social',
  'level',
  'standard',
  'behind',
  'abroad',
  'likewise',
  'meant',
  'frustration',
  'reference',
  'personality',
  'deny',
  'basic',
  'freedom',
  'experience',
  'sure',
  'prove',
  'free',
  'market',
  'economy',
  'democratically',
  'elect',
  'government',
  'prosperity',
  'freedom',
  'transition',
  'period',
  'citizen',
  'suffer',
  'sacrifice',
  'benefit',
  'benefit',
  'child',
  'grandchild',
  'basic',
  'asset',
  'undoubtedly',
  'quality',
  'population',
  'human',
  'resource',
  'proud',
  'educate',
  'population',
  'pretty',
  'standard',
  'scientific',
  'creative',
  'potential',
  'country',
  'boast',
  'strive',
  'standard',
  'strategic',
  'goal',
  'indeed',
  'tremendous',
  'achievement',
  'former',
  'utmost',
  'develop',
  'invaluable',
  'asset',
  'grant',
  'civilize',
  'opportunity',
  'development',
  'natural',
  'resource',
  'enormous',
  'wealth',
  'paradoxical',
  'world',
  'experience',
  'testifies',
  'country',
  'possess',
  'substantial',
  'natural',
  'resource',
  'fail',
  'dispose',
  'best',
  'possible',
  'consequently',
  'rate',
  'poor',
  'east',
  'asian',
  'country',
  'marked',
  'effective',
  'dynamic',
  'development',
  'happen',
  'country',
  'hardly',
  'boast',
  'natural',
  'resource',
  'emphasize',
  'actually',
  'paramount',
  'factor',
  'willpower',
  'energy',
  'persistence',
  'knowledge',
  'gold',
  'enable',
  'open',
  'door',
  'welfare',
  'independence',
  'negative',
  'world',
  'experience',
  'teacher',
  'unequivocally',
  'absence',
  'strategy',
  'ability',
  'realization',
  'thereof',
  'outweighs',
  'notorious',
  'potential',
  'natural',
  'resource',
  'hence',
  'major',
  'conclusion',
  'strategy',
  'persistently',
  'practice',
  'defiance',
  'difficulty',
  'wealth',
  'entrails',
  'earth',
  'property',
  'subsequent',
  'generation',
  'circumstance',
  'lull',
  'relaxation',
  'contrary',
  'government',
  'live',
  'though',
  'possess',
  'truly',
  'omnipotent',
  'factor',
  'represent',
  'vast',
  'land',
  'area',
  'arable',
  'land',
  'parameter',
  'common',
  'canada',
  'australia',
  'save',
  'though',
  'capital',
  'index',
  'level',
  'effectiveness',
  'productivity',
  'export',
  'potential',
  'realistic',
  'effective',
  'strategy',
  'financial',
  'asset',
  'seventh',
  'advantage',
  'consists',
  'political',
  'stability',
  'unity',
  'society',
  'proud',
  'manage',
  'escape',
  'direct',
  'confrontation',
  'society',
  'stabilize',
  'situation',
  'unfortunately',
  'developed',
  'post',
  'communist',
  'country',
  'fail',
  'gain',
  'gain',
  'overall',
  'stability',
  'consolidation',
  'unity',
  'feel',
  'family',
  'objective',
  'gain',
  'coordination',
  'advance',
  'thereto',
  'equality',
  'poverty',
  'misery',
  'construct',
  'egalitarianism',
  'naturally',
  'ethnic',
  'religious',
  'group',
  'grant',
  'priority',
  'strategic',
  'objective',
  'unity',
  'multiform',
  'group',
  'population',
  'reasonable',
  'combination',
  'personal',
  'social',
  'fundamental',
  'substantially',
  'consensus',
  'hierarchic',
  'tradition',
  'society',
  'society',
  'dramatically',
  'huge',
  'separate',
  'small',
  'group',
  'rich',
  'mass',
  'poor',
  'survive',
  'doom',
  'misery',
  'equally',
  'future',
  'country',
  'ethnic',
  'religious',
  'group',
  'exercise',
  'group',
  'grant',
  ...],
 ['situation',
  'country',
  'major',
  'direction',
  'domestic',
  'foreign',
  'policy',
  'democratization',
  'economic',
  'political',
  'reform',
  'century',
  'parliamentarian',
  'distinguish',
  'guest',
  'citizen',
  'fateful',
  'world',
  'dramatically',
  'change',
  'change',
  'russia',
  'experienced',
  'great',
  'shock',
  'month',
  'east',
  'market',
  'crisis',
  'asia',
  'threaten',
  'spread',
  'across',
  'world',
  'south',
  'india',
  'pakistan',
  'nuclear',
  'power',
  'stand',
  'impasse',
  'kashmir',
  'extremely',
  'complex',
  'situation',
  'southern',
  'border',
  'instability',
  'region',
  'difficulty',
  'neighbor',
  'affect',
  'situation',
  'though',
  'remain',
  'island',
  'stability',
  'calm',
  'global',
  'regional',
  'crisis',
  'understand',
  'complexity',
  'situation',
  'choice',
  'clear',
  'energy',
  'determination',
  'protect',
  'economy',
  'woman',
  'gather',
  'today',
  'moment',
  'decisive',
  'future',
  'point',
  'crossroad',
  'today',
  'hope',
  'fear',
  'danger',
  'great',
  'opportunity',
  'crisis',
  'test',
  'nation',
  'leader',
  'central',
  'asia',
  'decision',
  'today',
  'affect',
  'life',
  'affect',
  'life',
  'child',
  'grandchild',
  'decision',
  'affect',
  'neighbor',
  'region',
  'economy',
  'world',
  'future',
  'destiny',
  'great',
  'nation',
  'rest',
  'countryman',
  'countrywoman',
  'acknowledge',
  'pride',
  'enormous',
  'stride',
  'seven',
  'short',
  'free',
  'independent',
  'strengthen',
  'national',
  'security',
  'press',
  'priority',
  'post',
  'cold',
  'power',
  'define',
  'size',
  'country',
  'army',
  'rather',
  'productivity',
  'competitiveness',
  'economy',
  'creativity',
  'success',
  'diplomacy',
  'criterion',
  'might',
  'powerful',
  'indeed',
  'buffer',
  'peace',
  'border',
  'safety',
  'belt',
  'friendly',
  'frontier',
  'nation',
  'earth',
  'enemy',
  'multi',
  'vector',
  'diplomacy',
  'foreign',
  'policy',
  'successfully',
  'define',
  'sovereignty',
  'territorial',
  'integrity',
  'developed',
  'close',
  'relation',
  'global',
  'community',
  'do',
  'do',
  'foreign',
  'policy',
  'area',
  'laid',
  'special',
  'report',
  'distribute',
  'forth',
  'vision',
  'modern',
  'inherit',
  'child',
  'child',
  'child',
  'comprehensive',
  'report',
  'plan',
  'forth',
  'detailed',
  'road',
  'future',
  'prosperity',
  'security',
  'grow',
  'welfare',
  'road',
  'follow',
  'today',
  'read',
  'special',
  'report',
  'distribute',
  'do',
  'implementation',
  'strategy',
  'remember',
  'brief',
  'disruption',
  'detour',
  'journey',
  'force',
  'deal',
  'short',
  'economic',
  'crisis',
  'national',
  'emergency',
  'follow',
  'route',
  'milestone',
  'ultimately',
  'kind',
  'society',
  'dream',
  'nation',
  'democracy',
  'repress',
  'fifty',
  'world',
  'exist',
  'democratic',
  'political',
  'institution',
  'rapidly',
  'rebuilt',
  'democratic',
  'institution',
  'modern',
  'sense',
  'process',
  'building',
  'begin',
  'ground',
  'progress',
  'step',
  'step',
  'democratic',
  'culture',
  'population',
  'road',
  'longer',
  'difficult',
  'hand',
  'institution',
  'infrastructure',
  'mistake',
  'policy',
  'past',
  'advantage',
  'fresh',
  'start',
  'recommit',
  'vision',
  'future',
  'demonstrate',
  'strength',
  'vision',
  'courage',
  'stay',
  'course',
  'build',
  'built',
  'political',
  'justice',
  'economic',
  'freedom',
  'wisdom',
  'countryman',
  'wisdom',
  'choice',
  'clear',
  'reform',
  'regress',
  'streamline',
  'stagnate',
  'democratize',
  'decay',
  'build',
  'modem',
  'slide',
  'chaos',
  'today',
  'century',
  'base',
  'sound',
  'sensible',
  'value',
  'base',
  'economy',
  'built',
  'upon',
  'democratic',
  'principle',
  'structure',
  'procedure',
  'base',
  'effectiveness',
  'fairness',
  'government',
  'build',
  'strong',
  'secure',
  'play',
  'noticeable',
  'role',
  'world',
  'child',
  'reject',
  'religious',
  'extremism',
  'reject',
  'national',
  'extremism',
  'loudly',
  'reject',
  'political',
  'extremism',
  'government',
  'power',
  'vigorously',
  'fight',
  'extremism',
  'preserve',
  'develop',
  'democratic',
  'institution',
  'foresight',
  'action',
  'strong',
  'change',
  'specific',
  'economy',
  'challenge',
  'fold',
  'guide',
  'economy',
  'safely',
  'period',
  'severe',
  'financial',
  'crisis',
  'region',
  'place',
  'economy',
  'firm',
  'path',
  'recovery',
  'growth',
  'promising',
  'advance',
  'toward',
  'independent',
  'open',
  'free',
  'market',
  'economy',
  'ensure',
  'benefit',
  'robust',
  'economy',
  'directly',
  'impact',
  'quality',
  'life',
  'fundamental',
  'responsibility',
  'today',
  'mount',
  'broad',
  'forceful',
  'defense',
  'nation',
  'economic',
  'economic',
  'health',
  'approach',
  'external',
  'attack',
  'mobilize',
  'resource',
  'state',
  'develop',
  'comprehensive',
  'plan',
  'ensure',
  'strong',
  'courageous',
  'leadership',
  'program',
  'announce',
  'today',
  'goal',
  'direct',
  'prime',
  'minister',
  'convene',
  'economic',
  'policy',
  'council',
  'senior',
  'economic',
  'official',
  'government',
  'council',
  'chairman',
  'national',
  'bank',
  'permanent',
  'ensure',
  'coherence',
  'policy',
  'rapid',
  'response',
  'external',
  'internal',
  'crisis',
  'defend',
  'damage',
  'bank',
  'business',
  'consumer',
  'overall',
  'economy',
  'ensure',
  'national',
  'bank',
  'flexibility',
  'adopt',
  'exchange',
  'rate',
  'money',
  'supply',
  'control',
  'keep',
  'industry',
  'competitive',
  'world',
  'trade',
  'market',
  'bank',
  'design',
  'stand',
  'contingency',
  'program',
  'protect',
  'sudden',
  'external',
  'shock',
  'tighten',
  'control',
  'capital',
  'flow',
  'devaluation',
  'ruble',
  'change',
  'russian',
  'economy',
  'adverse',
  'impact',
  'business',
  'instruct',
  'national',
  'bank',
  'ministry',
  'energy',
  'industry',
  'trade',
  'closely',
  'monitor',
  'health',
  'bank',
  'enterprise',
  'turbulent',
  'period',
  'design',
  'safety',
  'protect',
  'internal',
  'economy',
  'consistent',
  'industrial',
  'policy',
  'developed',
  'ministry',
  'stimulate',
  'export',
  'replace',
  'import',
  'revival',
  'enterprise',
  'produce',
  'demand',
  'upon',
  'instruction',
  'government',
  'developed',
  'approach',
  'differentiation',
  'budget',
  'sector',
  'entrepreneurship',
  'creation',
  'present',
  'transparent',
  'budget',
  'respect',
  'program',
  'reform',
  'mechanism',
  'social',
  'protection',
  'scheme',
  'financing',
  'education',
  'medical',
  'care',

In [15]:
from gensim.models.phrases import Phrases, Phraser

phrase_mod = Phrases(sentences, min_count=10, 
                  threshold=0.7, scoring = 'npmi')

print(phrase_mod[sentences[0]])

['prosperity', 'security', 'grow', 'welfare', 'message', 'country', 'century', 'virgil', 'epoch', 'goal', 'heine', 'introduction', 'nothing', 'remote', 'yesterday', 'nothing', 'close', 'tomorrow', 'folk', 'proverb', 'fellow', 'citizen', 'appeal', 'share', 'vision', 'future', 'society', 'mission', 'state', 'want', 'present', 'strategy', 'sure', 'help', 'gain', 'future', 'accomplish', 'mission', 'wish', 'share', 'consideration', 'future', 'loom', 'ahead', 'century', 'millenium', 'pretty', 'remote', 'perspective', 'future', 'want', 'build', 'child', 'believe', 'ripen', 'profound', 'awareness', 'longer', 'live', 'merely', 'incessant', 'turmoil', 'settle', 'present', 'clear', 'knowledge', 'understand', 'construct', 'trajectory', 'highway', 'development', 'ensure', 'game', 'objetives', 'correct', 'identification', 'priority', 'choose', 'relevant', 'strategy', 'manifest', 'firm', 'persistence', 'follow', 'path', 'dispense', 'unnecessary', 'track', 'waste', 'energy', 'resource', 'provide', 'strategy', 'firmness', 'purpose', 'accomplish', 'goal', 'overcome', 'obstacle', 'block', 'hard', 'condition', 'tackle', 'today', 'deprive', 'hope', 'enthusiasm', 'clear', 'awareness', 'prospect', 'honest', 'presentation', 'eventual', 'difficulty', 'privation', 'empeding', 'help', 'mobilize', 'effort', 'citizen', 'society', 'settle', 'common', 'remeber', 'apart', 'goal', 'period', 'today', 'generation', 'bear', 'tremendous', 'responsibility', 'future', 'generation', 'responsibility', 'parent', 'grandparent', 'child', 'grandchild', 'child', 'grandchild', 'want', 'remote', 'future', 'healthy', 'educate', 'live', 'prosperous', 'democratic', 'society', 'live', 'peace', 'feel', 'safe', 'safe', 'child', 'feel', 'safe', 'walk', 'street', 'feel', 'safe', 'property', 'indeed', 'succeed', 'strong', 'state', 'friendly', 'relation', 'neighbour', 'whether', 'remote', 'close', 'today', 'answer', 'seemingly', 'simple', 'pretty', 'wisdom', 'remark', 'reach', 'goal', 'follow', 'path', 'mind', 'clear', 'vision', 'model', 'future', 'present', 'generally', 'specific', 'short', 'objective', 'wherefore', 'action', 'permanently', 'stick', 'certain', 'standard', 'verify', 'follow', 'whether', 'progress', 'track', 'whether', 'outstrip', 'development', 'behind', 'mentally', 'contrast', 'passing', 'process', 'repeat', 'somewhat', 'perception', 'scope', 'import', 'problem', 'ahead', 'feel', 'world', 'planet', 'large', 'help', 'feel', 'nag', 'breath', 'epoch', 'draw', 'near', 'state', 'emerge', 'world', 'epoch', 'powerful', 'empire', 'ottoman', 'austrian', 'hungarian', 'recently', 'soviet', 'union', 'today', 'building', 'state', 'market', 'economy', 'democracy', 'independent', 'state', 'trodden', 'path', 'similar', 'enough', 'today', 'live', 'epoch', 'grow', 'globalization', 'close', 'interrelationship', 'powerful', 'outer', 'force', 'inevitably', 'play', 'pretty', 'substantial', 'role', 'determine', 'future', 'clever', 'enough', 'intention', 'honest', 'analysis', 'external', 'internal', 'factor', 'development', 'chance', 'choose', 'identify', 'priority', 'elaborate', 'relevant', 'strategy', 'consolidation', 'history', 'unique', 'circumstance', 'sure', 'enough', 'ought', 'study', 'experience', 'country', 'advantage', 'auspicious', 'tendency', 'world', 'community', 'none', 'cop', 'enormous', 'indispensable', 'implementation', 'dream', 'hope', 'building', 'child', 'grandchild', 'proud', 'today', 'ready', 'yesterday', 'short', 'experience', 'knowledge', 'hardly', 'afford', 'unfavourable', 'circumstance', 'sort', 'instability', 'essence', 'precede', 'period', 'consist', 'eventual', 'survival', 'independent', 'state', 'stormy', 'condition', 'budding', 'transition', 'period', 'prognosticate', 'sheer', 'failure', 'cope', 'unprecedentedly', 'tremendous', 'building', 'state', 'social', 'economic', 'transformation', 'collapse', 'altogether', 'today', 'clear', 'withstood', 'trial', 'fly', 'colour', 'alive', 'kick', 'notwithstanding', 'obstacle', 'safely', 'emerge', 'abyss', 'chaos', 'disorder', 'present', 'stage', 'stabilization', 'successfully', 'settle', 'urgent', 'paramount', 'problem', 'chance', 'retrospective', 'analysis', 'trustworthy', 'evaluation', 'pass', 'afford', 'face', 'future', 'contemplate', 'perspective', 'development', 'elaborate', 'plan', 'experience', 'statehood', 'implement', 'political', 'economic', 'reform', 'knowledge', 'world', 'govern', 'tolerance', 'understand', 'gain', 'arduous', 'condition', 'strong', 'confident', 'frankly', 'speak', 'afford', 'solution', 'tomorrow', 'afford', 'wait', 'completion', 'reform', 'early', 'yesterday', 'might', 'late', 'tomorrow', 'strategic', 'plan', 'summons', 'effort', 'discipline', 'enhances', 'activity', 'plan', 'concentrate', 'state', 'pretty', 'narrow', 'range', 'priority', 'urge', 'government', 'daily', 'settle', 'strategy', 'enhances', 'daily', 'annual', 'activity', 'score', 'goal', 'enough', 'guideline', 'practice', 'realize', 'plan', 'contemplate', 'utterly', 'indispensable', 'ministry', 'department', 'organize', 'month', 'nearer', 'objective', 'public', 'servant', 'awareness', 'strategic', 'goal', 'priority', 'settle', 'waste', 'meddling', 'minor', 'daily', 'chore', 'decision', 'adopt', 'correlate', 'strategy', 'whereas', 'proper', 'concentrate', 'purposeful', 'onwards', 'annual', 'plan', 'priority', 'monitoring', 'answer', 'advanced', 'gain', 'objective', 'strategic', 'planning', 'strategic', 'control', 'accountability', 'responsibility', 'prerequisite', 'sustainable', 'steady', 'progress', 'consolidation', 'society', 'goal', 'unity', 'walk', 'group', 'population', 'strategy', 'settle', 'common', 'problem', 'feasible', 'duly', 'consideration', 'society', 'group', 'population', 'identify', 'relevant', 'priority', 'ensure', 'realization', 'thereof', 'do', 'atmosphere', 'cooperation', 'state', 'group', 'population', 'private', 'sector', 'message', 'elaborate', 'framework', 'constitutional', 'duty', 'annually', 'concern', 'basic', 'trend', 'domestic', 'foreign', 'policy', 'mention', 'state', 'society', 'large', 'global', 'vision', 'strategy', 'guide', 'coordinate', 'enable', 'draw', 'annual', 'plan', 'action', 'issue', 'consideration', 'message', 'subsequent', 'annual', 'message', 'devote', 'major', 'trend', 'domestic', 'foreign', 'policy', 'contain', 'evaluation', 'implementation', 'strategy', 'identify', 'specific', 'objective', 'whereabouts', 'today', 'occurs', 'moment', 'tide', 'life', 'brings', 'luck', 'avail', 'miss', 'happen', 'follow', 'shallow', 'water', 'disaster', 'shakespeare', 'bright', 'opportunity', 'suspect', 'encounter', 'dun', 'late', 'involve', 'pursue', 'major', 'strategic', 'goal', 'sovereign', 'independent', 'state', 'today', 'grant', 'remember', 'fairly', 'rare', 'occurrence', 'history', 'embark', 'implement', 'broad', 'scale', 'social', 'political', 'economic', 'transformation', 'goal', 'score', 'though', 'area', 'manifest', 'tangible', 'result', 'situation', 'profound', 'consideration', 'analyse', 'development', 'point', 'world', 'expertise', 'consequently', 'compare', 'progress', 'transformation', 'institution', 'best', 'world', 'experience', 'analyse', 'advantage', 'flaw', 'serve', 'indispensable', 'prelude', 'elaborate', 'strategy', 'start', 'analyse', 'domestic', 'advantage', 'external', 'opportunity', 'enjoys', 'weak', 'point', 'trouble', 'anticipate', 'country', 'proud', 'eight', 'advantage', 'laid', 'foundation', 'independent', 'sovereign', 'state', 'requisite', 'state', 'institution', 'passing', 'month', 'brings', 'great', 'experience', 'knowledge', 'development', 'state', 'completion', 'former', 'political', 'economic', 'seventy', 'dominate', 'life', 'today', 'altogether', 'state', 'utterly', 'political', 'economic', 'influence', 'transformation', 'unfold', 'society', 'though', 'wholly', 'unawares', 'change', 'dramatically', 'qualitatively', 'value', 'altogether', 'standard', 'human', 'relation', 'short', 'free', 'state', 'collective', 'world', 'outlook', 'replace', 'private', 'individual', 'event', 'reverse', 'aspect', 'life', 'sure', 'enough', 'discard', 'offer', 'secure', 'minimum', 'social', 'benefit', 'success', 'number', 'field', 'remember', 'fell', 'apart', 'prove', 'noncompetitive', 'economic', 'point', 'obviously', 'fail', 'social', 'level', 'standard', 'behind', 'abroad', 'likewise', 'meant', 'frustration', 'reference', 'personality', 'deny', 'basic', 'freedom', 'experience', 'sure', 'prove', 'free', 'market', 'economy', 'democratically', 'elect', 'government', 'prosperity', 'freedom', 'transition', 'period', 'citizen', 'suffer', 'sacrifice', 'benefit', 'benefit', 'child', 'grandchild', 'basic', 'asset', 'undoubtedly', 'quality', 'population', 'human', 'resource', 'proud', 'educate', 'population', 'pretty', 'standard', 'scientific', 'creative', 'potential', 'country', 'boast', 'strive', 'standard', 'strategic', 'goal', 'indeed', 'tremendous', 'achievement', 'former', 'utmost', 'develop', 'invaluable', 'asset', 'grant', 'civilize', 'opportunity', 'development', 'natural', 'resource', 'enormous', 'wealth', 'paradoxical', 'world', 'experience', 'testifies', 'country', 'possess', 'substantial', 'natural', 'resource', 'fail', 'dispose', 'best', 'possible', 'consequently', 'rate', 'poor', 'east', 'asian', 'country', 'marked', 'effective', 'dynamic', 'development', 'happen', 'country', 'hardly', 'boast', 'natural', 'resource', 'emphasize', 'actually', 'paramount', 'factor', 'willpower', 'energy', 'persistence', 'knowledge', 'gold', 'enable', 'open', 'door', 'welfare', 'independence', 'negative', 'world', 'experience', 'teacher', 'unequivocally', 'absence', 'strategy', 'ability', 'realization', 'thereof', 'outweighs', 'notorious', 'potential', 'natural', 'resource', 'hence', 'major', 'conclusion', 'strategy', 'persistently', 'practice', 'defiance', 'difficulty', 'wealth', 'entrails', 'earth', 'property', 'subsequent', 'generation', 'circumstance', 'lull', 'relaxation', 'contrary', 'government', 'live', 'though', 'possess', 'truly', 'omnipotent', 'factor', 'represent', 'vast', 'land', 'area', 'arable', 'land', 'parameter', 'common', 'canada', 'australia', 'save', 'though', 'capital', 'index', 'level', 'effectiveness', 'productivity', 'export', 'potential', 'realistic', 'effective', 'strategy', 'financial', 'asset', 'seventh', 'advantage', 'consists', 'political', 'stability', 'unity', 'society', 'proud', 'manage', 'escape', 'direct', 'confrontation', 'society', 'stabilize', 'situation', 'unfortunately', 'developed', 'post', 'communist', 'country', 'fail', 'gain', 'gain', 'overall', 'stability', 'consolidation', 'unity', 'feel', 'family', 'objective', 'gain', 'coordination', 'advance', 'thereto', 'equality', 'poverty', 'misery', 'construct', 'egalitarianism', 'naturally', 'ethnic', 'religious', 'group', 'grant', 'priority', 'strategic', 'objective', 'unity', 'multiform', 'group', 'population', 'reasonable', 'combination', 'personal', 'social', 'fundamental', 'substantially', 'consensus', 'hierarchic', 'tradition', 'society', 'society', 'dramatically', 'huge', 'separate', 'small', 'group', 'rich', 'mass', 'poor', 'survive', 'doom', 'misery', 'equally', 'future', 'country', 'ethnic', 'religious', 'group', 'exercise', 'group', 'grant', 'sort', 'benefit', 'opportunity', 'whereas', 'deny', 'political', 'party', 'movement', 'tear', 'society', 'apart', 'exists', 'enormous', 'unbalance', 'freedom', 'responsibility', 'mass', 'medium', 'liberalism', 'democracy', 'might', 'state', 'suffer', 'extreme', 'beware', 'awareness', 'sensible', 'social', 'consciousness', 'eight', 'emphasis', 'tolerance', 'patience', 'cordiality', 'affability', 'witness', 'foreigner', 'grateful', 'country', 'endure', 'hardship', 'privation', 'transition', 'period', 'understand', 'patience', 'deem', 'quality', 'pledge', 'success', 'consolidation', 'society', 'attract', 'foreign', 'investment', 'involvement', 'world', 'community', 'settle', 'problem', 'advantage', 'enjoy', 'number', 'opportunity', 'purely', 'external', 'nature', 'opportunity', 'sort', 'determine', 'geographical', 'geopolitical', 'economic', 'position', 'country', 'worth', 'distinguish', 'basic', 'opportunity', 'opportunity', 'stem', 'geographical', 'position', 'crossroad', 'eurasian', 'region', 'process', 'globalization', 'international', 'economic', 'political', 'process', 'factor', 'paramount', 'family', 'turkic', 'forefather', 'strategic', 'factor', 'advantage', 'legendary', 'silk', 'route', 'broad', 'channel', 'trade', 'european', 'asian', 'country', 'today', 'initiate', 'restoration', 'cooperation', 'country', 'pertain', 'region', 'substantiate', 'support', 'extend', 'world', 'community', 'future', 'trade', 'financial', 'flow', 'migration', 'europe', 'asia', 'rise', 'actually', 'reason', 'apart', 'politically', 'stabilize', 'factor', 'prompt', 'advance', 'develop', 'idea', 'eurasianism', 'sure', 'bright', 'strategic', 'future', 'hand', 'contiguous', 'country', 'unable', 'realize', 'profitable', 'transit', 'potential', 'do', 'jointly', 'close', 'mutually', 'advantageous', 'cooperation', 'situate', 'cross', 'road', 'afford', 'tremendous', 'potential', 'major', 'marketing', 'area', 'produce', 'perimeter', 'border', 'neighbour', 'market', 'embrace', 'absorb', 'rare', 'exception', 'product', 'provide', 'naturally', 'competible', 'network', 'transport', 'route', 'neighbour', 'russia_china', 'group', 'islamic', 'central_asian', 'state', 'country', 'near', 'middle_east', 'historically', 'represent', 'world', 'centre', 'peace', 'neighbourly', 'relation', 'confidence', 'eurasian', 'continent', 'indispensable', 'prerequisite', 'successful', 'development', 'country', 'involve', 'rivalry', 'competition', 'confrontation', 'impermissibly', 'waste', 'resource', 'energy', 'doom', 'stagnation', 'behind', 'support', 'lent', 'foreign', 'state', 'donor', 'agency', 'substantiate', 'laborious', 'process', 'state', 'construction', 'implementation', 'reform', 'offer', 'opportunity', 'compare', 'number', 'country', 'less', 'fortunate', 'factor', 'initial', 'stage', 'transition', 'period', 'financial', 'asset', 'knowledge', 'process', 'globalization', 'scientific', 'technical', 'progress', 'development', 'informational', 'telecommunication', 'technology', 'offer', 'unique', 'opportunity', 'vast', 'thinly', 'populate', 'country', 'nothing', 'guarantee', 'keep', 'abreast', 'process', 'rather', 'behind', 'consequently', 'utterly', 'indispensable', 'understand', 'technology', 'succeed', 'complete', 'integration', 'thereof', 'society', 'support', 'scientific', 'technological', 'personnel', 'speak', 'negative', 'feature', 'present', 'reality', 'note', 'weak', 'point', 'temporary', 'transitory', 'nature', 'rather', 'result', 'soviet', 'legacy', 'hardship', 'arduous', 'transition', 'period', 'mentality', 'shape', 'several', 'generation', 'brought', 'spirit', 'communist', 'principle', 'enthusiastically', 'advantage', 'recent', 'change', 'influence', 'subjective', 'objective', 'factor', 'slow', 'adapt', 'eventual', 'change', 'old', 'wait', 'assistance', 'render', 'state', 'solve', 'problem', 'philosophy', 'outlook', 'prevent', 'cop', 'difficulty', 'deprive', 'energy', 'wish', 'undertake', 'action', 'open', 'secret', 'official', 'understand', 'today', 'role', 'state', 'consist', 'decision', 'contrary', 'consist', 'shape', 'condition', 'free', 'citizen', 'private', 'sector', 'effective', 'measure', 'support', 'family', 'patient', 'transform', 'mass', 'consciousness', 'seek', 'support', 'young', 'generation', 'flexible', 'adapt', 'value', 'fresh', 'vision', 'future', 'state', 'unable', 'reverse', 'human', 'mentality', 'overnight', 'state', 'accelerate', 'process', 'change', 'elucidation', 'objective', 'trend', 'home', 'information', 'importantly', 'implement', 'social', 'economic', 'policie', 'sufficiency', 'world', 'outlook', 'existence', 'objectively', 'realization', 'economic', 'reform', 'disintegration', 'ussr', 'integration', 'economy', 'world', 'economic', 'relation', 'help', 'result', 'substantial', 'downfall', 'volume', 'production', 'consequently', 'deterioration', 'overall', 'social', 'situation', 'portion', 'technologically', 'outdated', 'power', 'consume', 'industry', 'poorly', 'train', 'hardly', 'cop', 'condition', 'economic', 'management', 'basic', 'factor', 'brought', 'competitiveness', 'shut', 'numerous', 'enterprise', 'loss', 'traditional', 'marketing', 'area', 'nonpayment', 'production', 'downfall', 'consequence', 'eight', 'country', 'suffer', 'fold', 'decline', 'level', 'production', 'budget', 'receipt', 'suffer', 'great', 'reduction', 'remember', 'downfall', 'coincide', 'rate', 'economic', 'growth', 'develop', 'country', 'implication', 'relative', 'economy', 'suffers', 'fold', 'behind', 'natural', 'figure', 'effectively', 'energetically', 'result', 'economic', 'downfall', 'witness', 'obvious', 'deterioration', 'income', 'standard', 'citizen', 'elimination', 'egalitarianism', 'creation', 'function', 'labour', 'market', 'result', 'grow', 'rich', 'poor', 'unfortunately', 'section', 'middle', 'class', 'major', 'support', 'state', 'basic', 'stabilization', 'factor', 'society', 'insignificant', 'national', 'saving', 'accumulation', 'capital', 'motive', 'force', 'economy', 'proceed', 'rather', 'slowly', 'consequently', 'short', 'internal', 'capital', 'saving', 'dependent', 'foreign', 'capital', 'private', 'international', 'financial', 'agency', 'rehabilitation', 'economy', 'depends', 'massive', 'influx', 'investment', 'possible', 'condition', 'eventual', 'improvement', 'investment', 'climate', 'painful', 'transition', 'command', 'administrative', 'economy', 'market', 'birth', 'acute', 'problem', 'poverty', 'unemployment', 'hitherto', 'unknown', 'wide_range', 'pave', 'crime', 'narcomania', 'rise', 'social', 'depression', 'build', 'potential', 'social', 'instability', 'tangible', 'unemployment', 'combine', 'delayed', 'payment', 'pension', 'wage', 'generate', 'mostly', 'economic', 'problem', 'shortage', 'financial', 'capital', 'strategy', 'inefficient', 'solution', 'lack', 'effective', 'programme', 'reform', 'agrarian', 'social', 'sector', 'health_care', 'education', 'science', 'reduction', 'budget', 'allocation', 'crucial', 'condition', 'transition', 'period', 'brought', 'deterioration', 'stagnation', 'vital', 'area', 'society', 'process', 'naturally', 'generate', 'weak', 'point', 'demographic', 'depopulation', 'fairly', 'dangerous', 'manifestation', 'post', 'start', 'witness', 'decrease', 'population', 'negative', 'seventh', 'aspect', 'poorly', 'prepared', 'inefficiently', 'organize', 'state', 'purely', 'feature', 'post', 'colonial', 'develop', 'post', 'communist', 'country', 'counter', 'phenomenon', 'today', 'solution', 'problem', 'depends', 'factor', 'cope', 'miserably', 'short', 'settle', 'strategic', 'problem', 'honestly', 'sense', 'patriotism', 'level', 'stand', 'habit', 'petty', 'interference', 'affair', 'altogether', 'unnecessary', 'harmful', 'halo', 'secrecy', 'prompt', 'concealment', 'information', 'society', 'bureaucracy', 'localistic', 'tendency', 'nepotism', 'clannishness', 'collective', 'irresponsibility', 'dullness', 'inertia', 'inadequate', 'multi', 'stage', 'hierarchy', 'corruption', 'complete', 'bunch', 'virtue', 'bureaucracy', 'brought', 'former', 'regime', 'fore', 'acquire', 'overt', 'undisguised', 'aspect', 'problem', 'surely', 'painfully', 'quality', 'corp', 'enterprise', 'manager', 'do', 'though', 'situation', 'resort', 'sort', 'administrative', 'surgery', 'obvious', 'problem', 'priority', 'head', 'state', 'follow', 'thought', 'reasonable', 'spare', 'certain', 'official', 'adapt', 'situation', 'expire', 'afford', 'kind', 'hearted', 'expense', 'endanger', 'destiny', 'country', 'besides', 'affect', 'development', 'country', 'seriously', 'undermine', 'potential', 'reproduction', 'pernicious', 'habit', 'step', 'capital', 'reform', 'government', 'staff', 'civil_servant', 'incompleteness', 'instability', 'legislation', 'enough', 'build', 'foundation', 'substantiate', 'floor', 'wall', 'roof', 'fairly', 'issue', 'whose', 'solution', 'determines', 'improvement

In [16]:
count_dict = dict(phrase_mod.vocab)
count_dict

{'prosperity': 33,
 'security': 247,
 'prosperity_security': 4,
 'grow': 116,
 'security_grow': 2,
 'welfare': 28,
 'grow_welfare': 4,
 'message': 13,
 'welfare_message': 1,
 'country': 1125,
 'message_country': 1,
 'century': 102,
 'country_century': 4,
 'virgil': 1,
 'century_virgil': 1,
 'epoch': 9,
 'virgil_epoch': 1,
 'goal': 177,
 'epoch_goal': 1,
 'heine': 1,
 'goal_heine': 1,
 'introduction': 86,
 'heine_introduction': 1,
 'nothing': 28,
 'introduction_nothing': 1,
 'remote': 21,
 'nothing_remote': 1,
 'yesterday': 6,
 'remote_yesterday': 1,
 'yesterday_nothing': 1,
 'close': 37,
 'nothing_close': 1,
 'tomorrow': 10,
 'close_tomorrow': 1,
 'folk': 6,
 'tomorrow_folk': 1,
 'proverb': 7,
 'folk_proverb': 2,
 'fellow': 30,
 'proverb_fellow': 1,
 'citizen': 510,
 'fellow_citizen': 27,
 'appeal': 41,
 'citizen_appeal': 2,
 'share': 78,
 'appeal_share': 1,
 'vision': 39,
 'share_vision': 1,
 'future': 248,
 'vision_future': 8,
 'society': 364,
 'future_society': 4,
 'mission': 26,
 'society_mission': 2,
 'state': 1116,
 'mission_state': 2,
 'want': 66,
 'state_want': 1,
 'present': 56,
 'want_present': 3,
 'strategy': 220,
 'present_strategy': 1,
 'sure': 34,
 'strategy_sure': 1,
 'help': 92,
 'sure_help': 1,
 'gain': 54,
 'help_gain': 1,
 'gain_future': 1,
 'accomplish': 22,
 'future_accomplish': 1,
 'accomplish_mission': 1,
 'wish': 24,
 'mission_wish': 1,
 'wish_share': 1,
 'consideration': 22,
 'share_consideration': 1,
 'consideration_future': 1,
 'loom': 1,
 'future_loom': 1,
 'ahead': 37,
 'loom_ahead': 1,
 'ahead_century': 1,
 'millenium': 2,
 'century_millenium': 1,
 'pretty': 8,
 'millenium_pretty': 1,
 'pretty_remote': 1,
 'perspective': 21,
 'remote_perspective': 2,
 'perspective_future': 2,
 'future_want': 1,
 'build': 95,
 'want_build': 3,
 'child': 206,
 'build_child': 1,
 'believe': 103,
 'child_believe': 2,
 'ripen': 1,
 'believe_ripen': 1,
 'profound': 8,
 'ripen_profound': 1,
 'awareness': 12,
 'profound_awareness': 1,
 'longer': 21,
 'awareness_longer': 1,
 'live': 57,
 'longer_live': 1,
 'merely': 4,
 'live_merely': 1,
 'incessant': 2,
 'merely_incessant': 1,
 'turmoil': 3,
 'incessant_turmoil': 1,
 'settle': 18,
 'turmoil_settle': 1,
 'settle_present': 1,
 'clear': 106,
 'present_clear': 1,
 'knowledge': 64,
 'clear_knowledge': 1,
 'understand': 76,
 'knowledge_understand': 1,
 'construct': 16,
 'understand_construct': 1,
 'trajectory': 3,
 'construct_trajectory': 1,
 'highway': 19,
 'trajectory_highway': 1,
 'development': 955,
 'highway_development': 2,
 'ensure': 378,
 'development_ensure': 5,
 'game': 8,
 'ensure_game': 1,
 'objetives': 1,
 'game_objetives': 1,
 'correct': 21,
 'objetives_correct': 1,
 'identification': 4,
 'correct_identification': 1,
 'priority': 232,
 'identification_priority': 1,
 'choose': 19,
 'priority_choose': 1,
 'relevant': 85,
 'choose_relevant': 1,
 'relevant_strategy': 2,
 'manifest': 6,
 'strategy_manifest': 1,
 'firm': 14,
 'manifest_firm': 1,
 'persistence': 2,
 'firm_persistence': 1,
 'follow': 120,
 'persistence_follow': 1,
 'path': 66,
 'follow_path': 6,
 'dispense': 1,
 'path_dispense': 1,
 'unnecessary': 11,
 'dispense_unnecessary': 1,
 'track': 19,
 'unnecessary_track': 1,
 'waste': 14,
 'track_waste': 1,
 'energy': 162,
 'waste_energy': 1,
 'resource': 227,
 'energy_resource': 7,
 'provide': 335,
 'resource_provide': 1,
 'provide_strategy': 1,
 'firmness': 2,
 'strategy_firmness': 1,
 'purpose': 77,
 'firmness_purpose': 1,
 'purpose_accomplish': 1,
 'accomplish_goal': 2,
 'overcome': 54,
 'goal_overcome': 1,
 'obstacle': 13,
 'overcome_obstacle': 3,
 'block': 11,
 'obstacle_block': 1,
 'hard': 27,
 'block_hard': 1,
 'condition': 238,
 'hard_condition': 1,
 'tackle': 13,
 'condition_tackle': 1,
 'today': 265,
 'tackle_today': 1,
 'deprive': 8,
 'today_deprive': 1,
 'hope': 25,
 'deprive_hope': 1,
 'enthusiasm': 4,
 'hope_enthusiasm': 1,
 'enthusiasm_clear': 1,
 'clear_awareness': 1,
 'prospect': 16,
 'awareness_prospect': 1,
 'honest': 13,
 'prospect_honest': 1,
 'presentation': 2,
 'honest_presentation': 1,
 'eventual': 7,
 'presentation_eventual': 1,
 'difficulty': 37,
 'eventual_difficulty': 1,
 'privation': 4,
 'difficulty_privation': 1,
 'empeding': 1,
 'privation_empeding': 1,
 'empeding_help': 1,
 'mobilize': 4,
 'help_mobilize': 1,
 'effort': 107,
 'mobilize_effort': 1,
 'effort_citizen': 3,
 'citizen_society': 4,
 'society_settle': 1,
 'common': 65,
 'settle_common': 2,
 'remeber': 1,
 'common_remeber': 1,
 'apart': 8,
 'remeber_apart': 1,
 'apart_goal': 1,
 'period': 100,
 'goal_period': 1,
 'period_today': 1,
 'generation': 87,
 'today_generation': 2,
 'bear': 24,
 'generation_bear': 1,
 'tremendous': 5,
 'bear_tremendous': 1,
 'responsibility': 171,
 'tremendous_responsibility': 1,
 'responsibility_future': 2,
 'future_generation': 12,
 'generation_responsibility': 1,
 'parent': 23,
 'responsibility_parent': 1,
 'grandparent': 1,
 'parent_grandparent': 1,
 'grandparent_child': 1,
 'grandchild': 10,
 'child_grandchild': 10,
 'grandchild_child': 1,
 'grandchild_want': 1,
 'want_remote': 1,
 'remote_future': 1,
 'healthy': 37,
 'future_healthy': 1,
 'educate': 21,
 'healthy_educate': 1,
 'educate_live': 1,
 'prosperous': 24,
 'live_prosperous': 1,
 'democratic': 55,
 'prosperous_democratic': 1,
 'democratic_society': 11,
 'society_live': 1,
 'peace': 48,
 'live_peace': 4,
 'feel': 21,
 'peace_feel': 1,
 'safe': 19,
 'feel_safe': 3,
 'safe_safe': 1,
 'safe_child': 1,
 'child_feel': 1,
 'walk': 6,
 'safe_walk': 1,
 'street': 11,
 'walk_street': 1,
 'street_feel': 1,
 'property': 60,
 'safe_property': 1,
 'indeed': 14,
 'property_indeed': 1,
 'succeed': 21,
 'indeed_succeed': 1,
 'strong': 113,
 'succeed_strong': 1,
 'strong_state': 14,
 'friendly': 19,
 'state_friendly': 1,
 'relation': 86,
 'friendly_relation': 4,
 'neighbour': 42,
 'relation_neighbour': 7,
 'whether': 18,
 'neighbour_whether': 1,
 'whether_remote': 1,
 'remote_close': 1,
 'close_today': 1,
 'answer': 19,
 'today_answer': 1,
 'seemingly': 4,
 'answer_seemingly': 2,
 'simple': 28,
 'seemingly_simple': 3,
 'simple_pretty': 1,
 'wisdom': 16,
 'pretty_wisdom': 1,
 'remark': 2,
 'wisdom_remark': 1,
 'reach': 82,
 'remark_reach': 1,
 'reach_goal': 6,
 'goal_follow': 3,
 'mind': 25,
 'path_mind': 1,
 'mind_clear': 1,
 'clear_vision': 6,
 'model': 122,
 'vision_model': 2,
 'model_future': 3,
 'future_present': 1,
 'generally': 9,
 'present_generally': 1,
 'specific': 106,
 'generally_specific': 1,
 'short': 35,
 'specific_short': 1,
 'objective': 68,
 'short_objective': 2,
 'wherefore': 1,
 'objective_wherefore': 1,
 'action': 116,
 'wherefore_action': 1,
 'permanently': 5,
 'action_permanently': 1,
 'stick': 6,
 'permanently_stick': 1,
 'certain': 55,
 'stick_certain': 1,
 'standard': 171,
 'certain_standard': 1,
 'verify': 2,
 'standard_verify': 1,
 'verify_follow': 1,
 'follow_whether': 1,
 'progress': 66,
 'whether_progress': 1,
 'progress_track': 1,
 'track_whether': 1,
 'outstrip': 1,
 'whether_outstrip': 1,
 'outstrip_development': 1,
 'behind': 22,
 'development_behind': 1,
 'mentally': 1,
 'behind_mentally': 1,
 'contrast': 1,
 'mentally_contrast': 1,
 'passing': 4,
 'contrast_passing': 1,
 'process': 213,
 'passing_process': 1,
 'repeat': 12,
 'process_repeat': 1,
 'somewhat': 1,
 'repeat_somewhat': 1,
 'perception': 4,
 'somewhat_perception': 1,
 'scope': 11,
 'perception_scope': 1,
 'import': 32,
 'scope_import': 1,
 'problem': 262,
 'import_problem': 1,
 'problem_ahead': 1,
 'ahead_feel': 1,
 'world': 439,
 'feel_world': 1,
 'planet': 6,
 'world_planet': 1,
 'large': 186,
 'planet_large': 1,
 'large_help': 1,
 'help_feel': 1,
 'nag': 1,
 'feel_nag': 1,
 'breath': 2,
 'nag_breath': 1,
 'breath_epoch': 1,
 'draw': 13,
 'epoch_draw': 1,
 'near': 47,
 'draw_near': 1,
 'near_state': 1,
 'emerge': 15,
 'state_emerge': 1,
 'emerge_world': 1,
 'world_epoch': 1,
 'powerful': 32,
 'epoch_powerful': 1,
 'empire': 5,
 'powerful_empire': 1,
 'ottoman': 1,
 'empire_ottoman': 1,
 'austrian': 1,
 'ottoman_austrian': 1,
 'hungarian': 1,
 'austrian_hungarian': 1,
 'recently': 28,
 'hungarian_recently': 1,
 'soviet': 27,
 'recently_soviet': 1,
 'union': 44,
 'soviet_union': 5,
 'union_today': 1,
 'building': 130,
 'today_building': 1,
 'building_state': 7,
 'market': 327,
 'state_market': 3,
 'economy': 533,
 'market_economy': 29,
 'democracy': 54,
 'economy_democracy': 1,
 'independent': 76,
 'democracy_independent': 1,
 'independent_state': 15,
 'trodden': 1,
 'state_trodden': 1,
 'trodden_path': 1,
 'similar': 20,
 'path_similar': 1,
 'enough': 32,
 'similar_enough': 1,
 'enough_today': 1,
 'today_live': 2,
 'live_epoch': 1,
 'epoch_grow': 1,
 'globalization': 8,
 'grow_globalization': 1,
 'globalization_close': 1,
 'interrelationship': 1,
 'close_interrelationship': 1,
 'interrelationship_powerful': 1,
 'outer': 1,
 'powerful_outer': 1,
 'force': 120,
 'outer_force': 1,
 'inevitably': 8,
 'force_inevitably': 1,
 'play': 47,
 'inevitably_play': 1,
 'play_pretty': 1,
 'substantial': 30,
 'pretty_substantial': 1,
 'role': 147,
 'substantial_role': 1,
 'determine': 47,
 'role_determine': 1,
 'determine_future': 2,
 'clever': 1,
 'future_clever': 1,
 'clever_enough': 1,
 'intention': 8,
 'enough_intention': 1,
 'intention_honest': 1,
 'analysis': 32,
 'honest_analysis': 1,
 'external': 55,
 'analysis_external': 1,
 'internal': 61,
 'external_internal': 3,
 'factor': 88,
 'internal_factor': 1,
 'factor_development': 5,
 'chance': 18,
 'development_chance': 2,
 'chance_choose': 1,
 'identify': 43,
 'choose_identify': 1,
 'identify_priority': 2,
 'elaborate': 26,
 'priority_elaborate': 2,
 'elaborate_relevant': 1,
 'consolidation': 20,
 'strategy_consolidation': 1,
 'history': 89,
 'consolidation_history': 1,
 'unique': 23,
 'history_unique': 1,
 'circumstance': 21,
 'unique_circumstance': 1,
 'circumstance_sure': 1,
 'sure_enough': 3,
 'ought': 6,
 'enough_ought': 1,
 'study': 50,
 'ought_study': 1,
 'experience': 113,
 'study_experience': 4,
 'experience_country': 7,
 'advantage': 52,
 'country_advantage': 1,
 'auspicious': 1,
 'advantage_auspicious': 1,
 'tendency': 11,
 'auspicious_tendency': 1,
 'tendency_world': 1,
 'community': 101,
 'world_community': 21,
 'none': 4,
 'community_none': 1,
 'cop': 3,
 'none_cop': 1,
 'enormous': 13,
 'cop_enormous': 1,
 'indispensable': 8,
 'enormous_indispensable': 1,
 'implementation': 189,
 'indispensable_implementation': 1,
 'dream': 19,
 'implementation_dream': 1,
 'dream_hope': 1,
 'hope_building': 1,
 'building_child': 1,
 'proud': 17,
 'grandchild_proud': 1,
 'proud_today': 1,
 'ready': 35,
 'today_ready': 1,
 'ready_yesterday': 1,
 'yesterday_short': 1,
 'short_experience': 1,
 'experience_knowledge': 3,
 'hardly': 9,
 'knowledge_hardly': 1,
 'afford': 19,
 'hardly_afford': 1,
 'unfavourable': 3,
 'afford_unfavourable': 1,
 'unfavourable_circumstance': 2,
 'sort': 6,
 'circumstance_sort': 1,
 'instability': 16,
 'sort_instability': 1,
 'essence': 18,
 'instability_essence': 1,
 'precede': 2,
 'essence_precede': 1,
 'precede_period': 1,
 'consist': 13,
 'period_consist': 1,
 'consist_eventual': 1,
 'survival': 9,
 'eventual_survival': 1,
 'survival_independent': 1,
 'stormy': 1,
 'state_stormy': 1,
 'stormy_condition': 1,
 'budding': 1,
 'condition_budding': 1,
 'transition': 76,
 'budding_transition': 1,
 'transition_period': 10,
 'prognosticate': 1,
 'period_prognosticate': 1,
 'sheer': 2,
 'prognosticate_sheer': 1,
 'failure': 20,
 'sheer_failure': 1,
 'cope': 9,
 'failure_cope': 1,
 'unprecedentedly': 1,
 'cope_unprecedentedly': 1,
 'unprecedentedly_tremendous': 1,
 'tremendous_building': 1,
 'social': 483,
 'state_social': 14,
 'economic': 559,
 'social_economic': 24,
 'transformation': 53,
 'economic_transformation': 7,
 'collapse': 14,
 'transformation_collapse': 1,
 'altogether': 6,
 'collapse_altogether': 1,
 'altogether_today': 1,
 'today_clear': 1,
 'withstood': 4,
 'clear_withstood': 1,
 'trial': 17,
 'withstood_trial': 1,
 'fly': 2,
 'trial_fly': 1,
 'colour': 3,
 'fly_colour': 2,
 'alive': 2,
 'colour_alive': 1,
 'kick': 2,
 'alive_kick': 1,
 'notwithstanding': 4,
 'kick_notwithstanding': 1,
 'notwithstanding_obstacle': 1,
 'safely': 3,
 'obstacle_safely': 1,
 'safely_emerge': 1,
 'abyss': 2,
 'emerge_abyss': 1,
 'chaos': 8,
 'abyss_chaos': 2,
 'disorder': 8,
 'chaos_disorder': 1,
 'disorder_present': 1,
 'stage': 87,
 'present_stage': 1,
 'stabilization': 8,
 'stage_stabilization': 1,
 'successfully': 37,
 'stabilization_successfully': 1,
 'successfully_settle': 1,
 'urgent': 28,
 'settle_urgent': 1,
 'paramount': 9,
 'urgent_paramount': 1,
 'paramount_problem': 1,
 'problem_chance': 1,
 'retrospective': 2,
 'chance_retrospective': 1,
 'retrospective_analysis': 1,
 'trustworthy': 1,
 'analysis_trustworthy': 1,
 'evaluation': 11,
 'trustworthy_evaluation': 1,
 'pass': 23,
 'evaluation_pass': 1,
 'pass_afford': 1,
 'face': 80,
 'afford_face': 1,
 'face_future': 1,
 'contemplate': 5,
 'future_contemplate': 1,
 'contemplate_perspective': 1,
 'perspective_development': 1,
 'development_elaborate': 1,
 'plan': 209,
 'elaborate_plan': 1,
 'plan_experience': 1,
 'statehood': 31,
 'experience_statehood': 1,
 'implement': 218,
 'statehood_implement': 1,
 'political': 351,
 'implement_political': 2,
 'political_economic': 18,
 'reform': 273,
 'economic_reform': 15,
 'reform_knowledge': 1,
 'knowledge_world': 2,
 'govern': 13,
 'world_govern': 1,
 'tolerance': 22,
 'govern_tolerance': 1,
 'tolerance_understand': 1,
 'understand_gain': 1,
 'arduous': 4,
 'gain_arduous': 1,
 'arduous_condition': 1,
 'condition_strong': 1,
 'confident': 32,
 'strong_confident': 1,
 'frankly': 6,
 'confident_frankly': 1,
 'speak': 33,
 'frankly_speak': 4,
 'speak_afford': 1,
 'solution': 64,
 'afford_solution': 1,
 'solution_tomorrow': 1,
 'tomorrow_afford': 1,
 'wait': 17,
 'afford_wait': 1,
 'completion': 11,
 'wait_completion': 1,
 'completion_reform': 1,
 'early': 45,
 'reform_early': 1,
 'early_yesterday': 1,
 'might': 19,
 'yesterday_might': 1,
 'late': 16,
 'might_late': 2,
 'late_tomorrow': 1,
 'strategic': 156,
 'tomorrow_strategic': 1,
 'strategic_plan': 17,
 'summons': 1,
 'plan_summons': 1,
 'summons_effort': 1,
 'discipline': 18,
 'effort_discipline': 1,
 'enhances': 3,
 'discipline_enhances': 1,
 'activity': 206,
 'enhances_activity': 1,
 'activity_plan': 1,
 'concentrate': 28,
 'plan_concentrate': 1,
 'concentrate_state': 1,
 'state_pretty': 1,
 'narrow': 7,
 'pretty_narrow': 1,
 'range': 28,
 'narrow_range': 1,
 'range_priority': 2,
 'urge': 12,
 'priority_urge': 1,
 'government': 1015,
 'urge_government': 2,
 'daily': 12,
 'government_daily': 1,
 'daily_settle': 1,
 'settle_strategy': 1,
 'strategy_enhances': 1,
 'enhances_daily': 1,
 'annual': 33,
 'daily_annual': 1,
 'annual_activity': 1,
 'score': 8,
 'activity_score': 1,
 'score_goal': 1,
 'goal_enough': 1,
 'guideline': 3,
 'enough_guideline': 1,
 'practice': 108,
 'guideline_practice': 1,
 'realize': 27,
 'practice_realize': 1,
 'realize_plan': 2,
 'plan_contemplate': 1,
 'utterly': 3,
 'contemplate_utterly': 1,
 'utterly_indispensable': 2,
 'ministry': 99,
 'indispensable_ministry': 1,
 'department': 23,
 'ministry_department': 3,
 'organize': 19,
 'department_organize': 1,
 'month': 47,
 'organize_month': 1,
 'nearer': 1,
 'month_nearer': 1,
 'nearer_objective': 1,
 'public': 378,
 'objective_public': 1,
 'servant': 60,
 'public_servant': 9,
 'servant_awareness': 1,
 'awareness_strategic': 1,
 'strategic_goal': 15,
 'goal_priority': 3,
 'priority_settle': 1,
 'settle_waste': 1,
 'meddling': 1,
 'waste_meddling': 1,
 'minor': 9,
 'meddling_minor': 1,
 'minor_daily': 1,
 'chore': 1,
 'daily_chore': 1,
 'decision': 126,
 'chore_decision': 1,
 'adopt': 140,
 'decision_adopt': 1,
 'correlate': 4,
 'adopt_correlate': 1,
 'correlate_strategy': 1,
 'whereas': 6,
 'strategy_whereas': 1,
 'proper': 17,
 'whereas_proper': 1,
 'proper_concentrate': 1,
 'purposeful': 5,
 'concentrate_purposeful': 1,
 'onwards': 3,
 'purposeful_onwards': 1,
 'onwards_annual': 1,
 'annual_plan': 2,
 'plan_priority': 4,
 'monitoring': 23,
 'priority_monitoring': 1,
 'monitoring_answer': 1,
 'advanced': 54,
 'answer_advanced': 1,
 'advanced_gain': 1,
 'gain_objective': 2,
 'objective_strategic': 1,
 'planning': 49,
 'strategic_planning': 10,
 'planning_strategic': 1,
 'control': 128,
 'strategic_control': 4,
 'accountability': 26,
 'control_accountability': 1,
 'accountability_responsibility': 1,
 'prerequisite': 13,
 'responsibility_prerequisite': 1,
 'sustainable': 56,
 'prerequisite_sustainable': 1,
 'steady': 12,
 'sustainable_steady': 1,
 'steady_progress': 3,
 'progress_consolidation': 1,
 'consolidation_society': 6,
 'society_goal': 2,
 'unity': 92,
 'goal_unity': 1,
 'unity_walk': 1,
 'group': 85,
 'walk_group': 1,
 'population': 185,
 'group_population': 12,
 'population_strategy': 1,
 'strategy_settle': 1,
 'common_problem': 3,
 'feasible': 5,
 'problem_feasible': 1,
 'duly': 3,
 'feasible_duly': 1,
 'duly_consideration': 1,
 'consideration_society': 1,
 'society_group': 1,
 'population_identify': 1,
 'identify_relevant': 2,
 'relevant_priority': 2,
 'priority_ensure': 5,
 'realization': 26,
 'ensure_realization': 1,
 'thereof': 13,
 'realization_thereof': 3,
 'do': 65,
 'thereof_do': 1,
 'atmosphere': 5,
 'do_atmosphere': 1,
 'cooperation': 79,
 'atmosphere_cooperation': 1,
 'cooperation_state': 1,
 'state_group': 1,
 'private': 188,
 'population_private': 1,
 'sector': 386,
 'private_sector': 47,
 'sector_message': 1,
 'message_elaborate': 1,
 'framework': 79,
 'elaborate_framework': 1,
 'constitutional': 34,
 'framework_constitutional': 1,
 'duty': 38,
 'constitutional_duty': 1,
 'annually': 22,
 'duty_annually': 1,
 'concern': 39,
 'annually_concern': 1,
 'basic': 91,
 'concern_basic': 1,
 'trend': 42,
 'basic_trend': 1,
 'domestic': 181,
 'trend_domestic': 2,
 'foreign': 213,
 'domestic_foreign': 28,
 'policy': 379,
 'foreign_policy': 49,
 'mention': 27,
 'policy_mention': 2,
 'mention_state': 2,
 'state_society': 17,
 'society_large': 2,
 'global': 222,
 'large_global': 3,
 'global_vision': 1,
 'vision_strategy': 2,
 'guide': 20,
 'strategy_guide': 2,
 'coordinate': 21,
 'guide_coordinate': 1,
 'enable': 31,
 'coordinate_enable': 1,
 'enable_draw': 1,
 'draw_annual': 1,
 'plan_action': 3,
 'issue': 384,
 'action_issue': 1,
 'issue_consideration': 1,
 'consideration_message': 1,
 'subsequent': 11,
 'message_subsequent': 1,
 'subsequent_annual': 1,
 'annual_message': 1,
 'devote': 7,
 'message_devote': 1,
 'major': 81,
 'devote_major': 1,
 'major_trend': 1,
 'contain': 5,
 'policy_contain': 1,
 'contain_evaluation': 1,
 'evaluation_implementation': 1,
 'implementation_strategy': 8,
 'strategy_identify': 3,
 'identify_specific': 2,
 'specific_objective': 2,
 'whereabouts': 1,
 'objective_whereabouts': 1,
 'whereabouts_today': 1,
 'occurs': 1,
 'today_occurs': 1,
 'moment': 16,
 'occurs_moment': 1,
 'tide': 3,
 'moment_tide': 1,
 'life': 184,
 'tide_life': 1,
 'brings': 8,
 'life_brings': 1,
 'luck': 2,
 'brings_luck': 1,
 'avail': 5,
 'luck_avail': 1,
 'miss': 6,
 'avail_miss': 1,
 'happen': 20,
 'miss_happen': 1,
 'happen_follow': 1,
 'shallow': 1,
 'follow_shallow': 1,
 'water': 135,
 'shallow_water': 1,
 'disaster': 10,
 'water_disaster': 1,
 'shakespeare': 1,
 'disaster_shakespeare': 1,
 'bright': 15,
 'shakespeare_bright': 1,
 'opportunity': 185,
 'bright_opportunity': 1,
 'suspect': 1,
 'opportunity_suspect': 1,
 'encounter': 3,
 'suspect_encounter': 1,
 'dun': 1,
 'encounter_dun': 1,
 'dun_late': 1,
 'involve': 80,
 'late_involve': 1,
 'pursue': 36,
 'involve_pursue': 1,
 'pursue_major': 1,
 'major_strategic': 1,
 'sovereign': 11,
 'goal_sovereign': 1,
 'sovereign_independent': 1,
 'state_today': 4,
 'grant': 56,
 'today_grant': 1,
 'remember': 34,
 'grant_remember': 1,
 'fairly': 7,
 'remember_fairly': 1,
 'rare': 9,
 'fairly_rare': 1,
 'occurrence': 2,
 'rare_occurrence': 1,
 'occurrence_history': 1,
 'embark': 7,
 'history_embark': 1,
 'embark_implement': 1,
 'broad': 29,
 'implement_broad': 2,

In [17]:
from gensim.models.phrases import npmi_scorer

npmi_scorer(count_dict['nurly'], count_dict['zhol'],
                count_dict['nurly_zhol'], len(phrase_mod.vocab),
                phrase_mod.min_count, phrase_mod.corpus_word_count)

0.955493225134465

In [18]:
bigram = dict() # пустой словарь для записи фильтрованных значений

for (key, value) in count_dict.items():
    if '_' in key:
        bigram[key] = value
        
bigram = pd.DataFrame.from_dict(bigram, orient = 'index').reset_index().rename(columns={"index": "Bigram", 0: "Count_B"})

In [19]:
top_500_bigrams = bigram.sort_values(by='Count_B', ascending=False).head(500)
top_500_bigrams

                    Bigram  Count_B
13668  instruct_government      137
1413       economic_growth      101
7580          small_medium       67
14150          medium_size       65
7417         national_bank       59
...                    ...      ...
2533      personnel_policy        8
15773    specific_proposal        8
1588      solution_problem        8
34286       akims_governor        8
16864       gas_processing        8

[500 rows x 2 columns]

In [20]:
scored_phrases = list(phrase_mod.export_phrases())
sorted_phrases = sorted(scored_phrases, key=lambda x: x[1], reverse=True)

sorted_phrases

['russia_china',
 'supreme_court',
 'european_union',
 'mutually_beneficial',
 'nurly_zhol',
 'otan_party',
 'prime_minister',
 'drug_traffic',
 'drinking_water',
 'transport_logistics',
 'private_partnership',
 'prosecutor_office',
 'artificial_intelligence',
 'square_metre',
 'solid_foundation',
 'socially_vulnerable',
 'corporate_governance',
 'inter_ethnic',
 'internal_affair',
 'small_medium',
 'electric_shock',
 'middle_east',
 'wide_range',
 'civil_servant',
 'oil_gas',
 'minimum_wage',
 'million_square',
 'shock_electric',
 'agro_industrial',
 'central_asian',
 'health_care',
 'territorial_integrity',
 'central_asia',
 'religious_extremism',
 'medium_size',
 'healthy_lifestyle',
 'large_scale',
 'labour_productivity',
 'samruk_kazyna']

In [21]:
proc_list = list(df_test['full_text_clean'])
proc_list = [phrase_mod[sublist] for sublist in proc_list]   
df_test['txt_clean_final'] = proc_list

In [22]:
df_test

,Title,Month,Year,Full Text,full_text_clean,txt_clean_final
0,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, grow, welfare, message,...","[prosperity, security, grow, welfare, message,..."
1,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti...","[situation, country, major, direction, domesti..."
2,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, century, genera...","[stability, security, country, century, genera..."
3,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[free, effective, secure, society, date, histo...","[free, effective, secure, society, date, histo..."
4,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, direction, domestic, fore...","[situation, country, direction, domestic, fore..."
5,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[direction, domestic, foreign, policy, deputy,...","[direction, domestic, foreign, policy, deputy,..."
6,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, develop, successfully, accordance, s...","[country, develop, successfully, accordance, s..."
7,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, confidence, optimism, national, economi...","[past, confidence, optimism, national, economi..."
8,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[road, accelerate, economic, social, political...","[road, accelerate, economic, social, political..."
9,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[strategy, join, world, competitive, country, ...","[strategy, join, world, competitive, country, ..."
10,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[world, deputy, government, lady, gentleman, i...","[world, deputy, government, lady, gentleman, i..."
11,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[growth, welfare, citizen, primary, goal, stat...","[growth, welfare, citizen, primary, goal, stat..."
12,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, today, world, d...","[crisis, renewal, development, today, world, d..."
13,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[economic, upswing, opportunity, difficult, pe...","[economic, upswing, opportunity, difficult, pe..."
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, deputy, government, lady, g...","[building, future, deputy, government, lady, g..."
15,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[leader, nation, strategy, political, course, ...","[leader, nation, strategy, political, course, ..."
16,Address by the President of the Republic of Ka...,December,2012,al and professional growth. The state and the ...,"[growth, state, understand, instill, patriotis...","[growth, state, understand, instill, patriotis..."
17,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[socio, economic, modernization, vector, devel...","[socio, economic, modernization, vector, devel..."
18,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[common, common, interest, common, future, fel...","[common, common, interest, common, future, fel..."
19,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[modernization, global, competitiveness, appro...","[modernization, global, competitiveness, appro..."
20,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[opportunity, industrial, revolution, today, w...","[opportunity, industrial, revolution, today, w..."
21,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, citizen, increase, income, qua...","[grow, welfare, citizen, increase, income, qua..."
22,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[state, nation, constructive, public, dialogue...","[state, nation, constructive, public, dialogue..."
23,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[reality, action, session, begin, challenge, c...","[reality, action, session, begin, challenge, c..."
24,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, systemic, reform, solid, foundation, n...","[unity, systemic, reform, solid_foundation, na..."
25,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[path, renewal, modernisation, friend, today, ...","[path, renewal, modernisation, friend, today, ..."
26,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[state, nation, fair, state, nation, prosperou...","[state, nation, fair, state, nation, prosperou..."
27,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[distinguish, government, accordance, article,...","[distinguish, government, accordance, article,..."
28,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[opening, regular, session, wish, success, act...","[opening, regular, session, wish, success, act..."

In [23]:
df_test.drop(columns=['full_text_clean'], inplace=True)

In [24]:
df_test

,Title,Month,Year,Full Text,txt_clean_final
0,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, grow, welfare, message,..."
1,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti..."
2,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, century, genera..."
3,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[free, effective, secure, society, date, histo..."
4,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, direction, domestic, fore..."
5,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[direction, domestic, foreign, policy, deputy,..."
6,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, develop, successfully, accordance, s..."
7,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, confidence, optimism, national, economi..."
8,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[road, accelerate, economic, social, political..."
9,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[strategy, join, world, competitive, country, ..."
10,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[world, deputy, government, lady, gentleman, i..."
11,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[growth, welfare, citizen, primary, goal, stat..."
12,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, today, world, d..."
13,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[economic, upswing, opportunity, difficult, pe..."
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, deputy, government, lady, g..."
15,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[leader, nation, strategy, political, course, ..."
16,Address by the President of the Republic of Ka...,December,2012,al and professional growth. The state and the ...,"[growth, state, understand, instill, patriotis..."
17,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[socio, economic, modernization, vector, devel..."
18,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[common, common, interest, common, future, fel..."
19,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[modernization, global, competitiveness, appro..."
20,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[opportunity, industrial, revolution, today, w..."
21,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, citizen, increase, income, qua..."
22,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[state, nation, constructive, public, dialogue..."
23,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[reality, action, session, begin, challenge, c..."
24,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, systemic, reform, solid_foundation, na..."
25,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[path, renewal, modernisation, friend, today, ..."
26,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[state, nation, fair, state, nation, prosperou..."
27,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[distinguish, government, accordance, article,..."
28,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[opening, regular, session, wish, success, act..."

In [25]:
row1 = df_test.loc[15]
row2 = df_test.loc[16]

row2

Title              Address by the President of the Republic of Ka...
Month                                                       December
Year                                                            2012
Full Text          al and professional growth. The state and the ...
txt_clean_final    [growth, state, understand, instill, patriotis...
Name: 16, dtype: object

In [26]:
merged_row = row1.copy()
merged_row['Full Text'] = row1['Full Text'] + row2['Full Text']  
merged_row['txt_clean_final'] = row1['txt_clean_final'] + row2['txt_clean_final'] 
df_test = df_test.drop([15, 16])
df_test = pd.concat([
    df_test.iloc[:15],
    pd.DataFrame([merged_row]),
    df_test.iloc[15:]
]).reset_index(drop=True)

In [27]:
#df_test.to_csv("tm_no_splits.csv", index=False)

In [ ]:
#df_test['word_count_before'] = df_test['Full Text'].apply(lambda x: len(str(x).split()))
#df_test['word_count_after'] = df_test['txt_clean_final'].apply(len)

df_test

,Title,Month,Year,Full Text,txt_clean_final
0,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, grow, welfare, message,..."
1,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti..."
2,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, century, genera..."
3,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[free, effective, secure, society, date, histo..."
4,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, direction, domestic, fore..."
5,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[direction, domestic, foreign, policy, deputy,..."
6,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, develop, successfully, accordance, s..."
7,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, confidence, optimism, national, economi..."
8,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[road, accelerate, economic, social, political..."
9,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[strategy, join, world, competitive, country, ..."
10,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[world, deputy, government, lady, gentleman, i..."
11,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[growth, welfare, citizen, primary, goal, stat..."
12,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, today, world, d..."
13,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[economic, upswing, opportunity, difficult, pe..."
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, deputy, government, lady, g..."
15,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[leader, nation, strategy, political, course, ..."
16,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[socio, economic, modernization, vector, devel..."
17,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[common, common, interest, common, future, fel..."
18,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[modernization, global, competitiveness, appro..."
19,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[opportunity, industrial, revolution, today, w..."
20,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, citizen, increase, income, qua..."
21,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[state, nation, constructive, public, dialogue..."
22,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[reality, action, session, begin, challenge, c..."
23,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, systemic, reform, solid_foundation, na..."
24,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[path, renewal, modernisation, friend, today, ..."
25,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[state, nation, fair, state, nation, prosperou..."
26,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[distinguish, government, accordance, article,..."
27,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[opening, regular, session, wish, success, act..."

In [29]:
cov_df = pd.read_csv("covariets.csv")
df_merged = df_test.merge(cov_df, on=['Month', 'Year'], how='left')
cov_df

,Month,Year,GDP,Real GDP,FDI,inflation (in % to the previous month),Inlfation (% to the corresponding month of the previous year),unemployment rate (%)
0,October,1997,2.216593e+10,5.982470e+10,1.321400e+09,1.1,11.7,13.0
1,September,1998,2.213525e+10,5.868803e+10,1.151400e+09,-0.1,6.2,13.1
2,September,1999,1.687082e+10,6.027261e+10,1.587000e+09,0.7,12.8,13.5
3,October,2000,1.829199e+10,6.617933e+10,1.370521e+09,1.2,10.4,12.8
4,September,2001,2.215269e+10,7.511354e+10,2.816823e+09,0.2,8.0,10.5
5,April,2002,2.463660e+10,8.247466e+10,2.588491e+09,0.5,4.8,9.3
6,April,2003,3.083369e+10,9.014481e+10,2.483253e+09,0.4,7.0,8.8
7,March,2004,4.315165e+10,9.879871e+10,5.615263e+09,0.4,6.5,8.4
8,February,2005,5.712367e+10,1.083822e+11,2.546066e+09,0.6,6.9,8.1
9,March,2006,8.100386e+10,1.199791e+11,7.611168e+09,0.8,8.9,7.8
10,February,2007,1.048499e+11,1.306572e+11,1.197284e+10,0.8,7.9,7.3
11,February,2008,1.334416e+11,1.349689e+11,1.681889e+10,0.8,18.8,6.6
12,March,2009,1.153087e+11,1.365885e+11,1.427589e+10,0.8,8.9,6.6
13,January,2010,1.480473e+11,1.465595e+11,7.456118e+09,1.4,7.3,5.8
14,January,2011,1.926265e+11,1.574049e+11,1.376029e+10,1.7,8.1,5.4
15,December,2012,2.079986e+11,1.649603e+11,1.364813e+10,0.7,5.6,5.3
16,January,2012,2.079986e+11,1.649603e+11,1.364813e+10,0.3,5.9,5.3
17,January,2014,2.214156e+11,1.822020e+11,7.308113e+09,0.6,4.5,5.1
18,January,2017,1.668058e+11,1.940598e+11,4.757397e+09,0.8,7.9,4.9
19,January,2018,1.793400e+11,2.020162e+11,3.532916e+08,0.6,6.8,4.8
20,October,2018,1.793400e+11,2.020162e+11,3.532916e+08,0.4,5.3,4.8
21,September,2019,1.816672e+11,2.111069e+11,3.730856e+09,0.3,5.3,4.8
22,September,2020,1.710824e+11,2.058293e+11,7.205989e+09,0.3,7.0,4.9
23,September,2021,1.971123e+11,2.146799e+11,4.566615e+09,0.4,8.9,4.9
24,March,2022,2.254963e+11,2.215497e+11,5.077497e+09,3.7,12.0,4.9
25,September,2022,2.254963e+11,2.215497e+11,5.077497e+09,1.8,17.7,4.9
26,September,2023,2.626419e+11,2.328487e+11,5.437312e+09,0.6,11.8,4.8
27,September,2024,2.685500e+11,2.410031e+11,1.974000e+10,0.4,8.3,4.8

In [30]:
df_merged

,Title,Month,Year,Full Text,txt_clean_final,GDP,Real GDP,FDI,inflation (in % to the previous month),Inlfation (% to the corresponding month of the previous year),unemployment rate (%)
0,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, grow, welfare, message,...",2.216593e+10,5.982470e+10,1.321400e+09,1.1,11.7,13.0
1,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti...",2.213525e+10,5.868803e+10,1.151400e+09,-0.1,6.2,13.1
2,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, century, genera...",1.687082e+10,6.027261e+10,1.587000e+09,0.7,12.8,13.5
3,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[free, effective, secure, society, date, histo...",1.829199e+10,6.617933e+10,1.370521e+09,1.2,10.4,12.8
4,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, direction, domestic, fore...",2.215269e+10,7.511354e+10,2.816823e+09,0.2,8.0,10.5
5,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[direction, domestic, foreign, policy, deputy,...",2.463660e+10,8.247466e+10,2.588491e+09,0.5,4.8,9.3
6,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, develop, successfully, accordance, s...",3.083369e+10,9.014481e+10,2.483253e+09,0.4,7.0,8.8
7,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, confidence, optimism, national, economi...",4.315165e+10,9.879871e+10,5.615263e+09,0.4,6.5,8.4
8,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[road, accelerate, economic, social, political...",5.712367e+10,1.083822e+11,2.546066e+09,0.6,6.9,8.1
9,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[strategy, join, world, competitive, country, ...",8.100386e+10,1.199791e+11,7.611168e+09,0.8,8.9,7.8
10,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[world, deputy, government, lady, gentleman, i...",1.048499e+11,1.306572e+11,1.197284e+10,0.8,7.9,7.3
11,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[growth, welfare, citizen, primary, goal, stat...",1.334416e+11,1.349689e+11,1.681889e+10,0.8,18.8,6.6
12,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, today, world, d...",1.153087e+11,1.365885e+11,1.427589e+10,0.8,8.9,6.6
13,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[economic, upswing, opportunity, difficult, pe...",1.480473e+11,1.465595e+11,7.456118e+09,1.4,7.3,5.8
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, deputy, government, lady, g...",1.926265e+11,1.574049e+11,1.376029e+10,1.7,8.1,5.4
15,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[leader, nation, strategy, political, course, ...",2.079986e+11,1.649603e+11,1.364813e+10,0.7,5.6,5.3
16,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[socio, economic, modernization, vector, devel...",2.079986e+11,1.649603e+11,1.364813e+10,0.3,5.9,5.3
17,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[common, common, interest, common, future, fel...",2.214156e+11,1.822020e+11,7.308113e+09,0.6,4.5,5.1
18,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[modernization, global, competitiveness, appro...",1.668058e+11,1.940598e+11,4.757397e+09,0.8,7.9,4.9
19,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[opportunity, industrial, revolution, today, w...",1.793400e+11,2.020162e+11,3.532916e+08,0.6,6.8,4.8
20,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, citizen, increase, income, qua...",1.793400e+11,2.020162e+11,3.532916e+08,0.4,5.3,4.8
21,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[state, nation, constructive, public, dialogue...",1.816672e+11,2.111069e+11,3.730856e+09,0.3,5.3,4.8
22,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[reality, action, session, begin, challenge, c...",1.710824e+11,2.058293e+11,7.205989e+09,0.3,7.0,4.9
23,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, systemic, reform, solid_foundation, na...",1.971123e+11,2.146799e+11,4.566615e+09,0.4,8.9,4.9
24,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[path, renewal, modernisation, friend, today, ...",2.254963e+11,2.215497e+11,5.077497e+09,3.7,12.0,4.9
25,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[state, nation, fair, state, nation, prosperou...",2.254963e+11,2.215497e+11,5.077497e+09,1.8,17.7,4.9
26,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[distinguish, government, accordance, article,...",2.626419e+11,2.328487e+11,5.437312e+09,0.6,11.8,4.8
27,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[opening, regular, session, wish, success, act...",2.685500e+11,2.410031e+11,1.974000e+10,0.4,8.3,4.8

In [31]:
# Create boolean columns based on year
df_merged['is_Nazarbayev'] = (df_merged['Year'] <= 2018).astype(int)
df_merged['is_Tokayev'] = (df_merged['Year'] > 2018).astype(int)
df_merged

,Title,Month,Year,Full Text,txt_clean_final,GDP,Real GDP,FDI,inflation (in % to the previous month),Inlfation (% to the corresponding month of the previous year),unemployment rate (%),is_Nazarbayev,is_Tokayev
0,Address of the President of the Republic of Ka...,October,1997,"PROSPERITY, SECURITY\n\nAND EVER GROWING WELFA...","[prosperity, security, grow, welfare, message,...",2.216593e+10,5.982470e+10,1.321400e+09,1.1,11.7,13.0,1,0
1,Address of the President of the Republic of Ka...,September,1998,On the Situation in the Country and major Dire...,"[situation, country, major, direction, domesti...",2.213525e+10,5.868803e+10,1.151400e+09,-0.1,6.2,13.1,1,0
2,Address of the President of the Republic of Ka...,September,1999,STABILITY AND SECURITY\nCOUNTRIES IN THE NEW C...,"[stability, security, country, century, genera...",1.687082e+10,6.027261e+10,1.587000e+09,0.7,12.8,13.5,1,0
3,Address of the President of the Republic of Ka...,October,2000,"Towards Free, Effective and Secure Society\n\n...","[free, effective, secure, society, date, histo...",1.829199e+10,6.617933e+10,1.370521e+09,1.2,10.4,12.8,1,0
4,Address of the President of the Republic of Ka...,September,2001,On the Situation in the Country and Main Direc...,"[situation, country, direction, domestic, fore...",2.215269e+10,7.511354e+10,2.816823e+09,0.2,8.0,10.5,1,0
5,Address of the President of the Republic of Ka...,April,2002,ON THE MAIN DIRECTIONS OF DOMESTIC AND FOREIGN...,"[direction, domestic, foreign, policy, deputy,...",2.463660e+10,8.247466e+10,2.588491e+09,0.5,4.8,9.3,1,0
6,Address of the President of the Republic of Ka...,April,2003,Our country continues to develop successfully ...,"[country, develop, successfully, accordance, s...",3.083369e+10,9.014481e+10,2.483253e+09,0.4,7.0,8.8,1,0
7,Address of the President of the Republic of Ka...,March,2004,The past year has added to our confidence and ...,"[past, confidence, optimism, national, economi...",4.315165e+10,9.879871e+10,5.615263e+09,0.4,6.5,8.4,1,0
8,Address of the President of the Republic of Ka...,February,2005,“Kazakhstan on the Road to Accelerated Economi...,"[road, accelerate, economic, social, political...",5.712367e+10,1.083822e+11,2.546066e+09,0.6,6.9,8.1,1,0
9,Address of the President of the Republic of Ka...,March,2006,Kazakhstan’s strategy of joining the world’s 5...,"[strategy, join, world, competitive, country, ...",8.100386e+10,1.199791e+11,7.611168e+09,0.8,8.9,7.8,1,0
10,Address of the President of the Republic of Ka...,February,2007,A new Kazakhstan in a new world\n\nDear deputi...,"[world, deputy, government, lady, gentleman, i...",1.048499e+11,1.306572e+11,1.197284e+10,0.8,7.9,7.3,1,0
11,Address of the President of the Republic of Ka...,February,2008,Address of the President of the Republic of Ka...,"[growth, welfare, citizen, primary, goal, stat...",1.334416e+11,1.349689e+11,1.681889e+10,0.8,18.8,6.6,1,0
12,Address of the President of the Republic of Ka...,March,2009,Through crisis to renewal and development \n\n...,"[crisis, renewal, development, today, world, d...",1.153087e+11,1.365885e+11,1.427589e+10,0.8,8.9,6.6,1,0
13,Address of the President of the Republic of Ka...,January,2010,The new decade is. The new economic upswing - ...,"[economic, upswing, opportunity, difficult, pe...",1.480473e+11,1.465595e+11,7.456118e+09,1.4,7.3,5.8,1,0
14,Address of the President of the Republic of Ka...,January,2011,Building the Future Together\n\nAddress of the...,"[building, future, deputy, government, lady, g...",1.926265e+11,1.574049e+11,1.376029e+10,1.7,8.1,5.4,1,0
15,Address by the President of the Republic of Ka...,December,2012,ADDRESS BY THE PRESIDENT OF THE REPUBLIC OF KA...,"[leader, nation, strategy, political, course, ...",2.079986e+11,1.649603e+11,1.364813e+10,0.7,5.6,5.3,1,0
16,Address by the President of the Republic of Ka...,January,2012,Address of the President of the Republic of Ka...,"[socio, economic, modernization, vector, devel...",2.079986e+11,1.649603e+11,1.364813e+10,0.3,5.9,5.3,1,0
17,Address of the President of the Republic of K...,January,2014,"Kazakhstan’s way – 2050:\n\ncommon aim, common...","[common, common, interest, common, future, fel...",2.214156e+11,1.822020e+11,7.308113e+09,0.6,4.5,5.1,1,0
18,The President of Kazakhstan Nursultan Nazarbay...,January,2017,"""Third Modernization of Kazakhstan: Global Com...","[modernization, global, competitiveness, appro...",1.668058e+11,1.940598e+11,4.757397e+09,0.8,7.9,4.9,1,0
19,State of the Nation Address by the President o...,January,2018,NEW OPPORTUNITIES UNDER THE FOURTH INDUSTRIAL ...,"[opportunity, industrial, revolution, today, w...",1.793400e+11,2.020162e+11,3.532916e+08,0.6,6.8,4.8,1,0
20,State of the Nation Address of President of th...,October,2018,GROWING WELFARE OF KAZAKH CITIZENS: INCREASE I...,"[grow, welfare, citizen, increase, income, qua...",1.793400e+11,2.020162e+11,3.532916e+08,0.4,5.3,4.8,1,0
21,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2019,President Kassym-Jomart Tokayev’s State of the...,"[state, nation, constructive, public, dialogue...",1.816672e+11,2.111069e+11,3.730856e+09,0.3,5.3,4.8,0,1
22,President of Kazakhstan Kassym-Jomart Tokayev’...,September,2020,KAZAKHSTAN IN A NEW REALITY: TIME FOR ACTION\n...,"[reality, action, session, begin, challenge, c...",1.710824e+11,2.058293e+11,7.205989e+09,0.3,7.0,4.9,0,1
23,State of the Nation Address by President of th...,September,2021,UNITY OF THE PEOPLE AND SYSTEMIC REFORMS ARE A...,"[unity, systemic, reform, solid_foundation, na...",1.971123e+11,2.146799e+11,4.566615e+09,0.4,8.9,4.9,0,1
24,State-of-the-Nation Address by President of th...,March,2022,NEW KAZAKHSTAN: THE PATH OF RENEWAL AND MODERN...,"[path, renewal, modernisation, friend, today, ...",2.254963e+11,2.215497e+11,5.077497e+09,3.7,12.0,4.9,0,1
25,President Kassym-Jomart Tokayev’s State of the...,September,2022,PRESIDENT KASSYM-JOMART TOKAYEV’S\n\nSTATE OF ...,"[state, nation, fair, state, nation, prosperou...",2.254963e+11,2.215497e+11,5.077497e+09,1.8,17.7,4.9,0,1
26,President Kassym-Jomart Tokayev`s State of the...,September,2023,"Dear Compatriots, Distinguished Members of Par...","[distinguish, government, accordance, article,...",2.626419e+11,2.328487e+11,5.437312e+09,0.6,11.8,4.8,0,1
27,President Kassym-Jomart Tokayev’s State of the...,September,2024,Dear Members of Parliament!\n\nCongratulations...,"[opening, regular, session, wish, success, act...",2.685500e+11,2.410031e+11,1.974000e+10,0.4,8.3,4.8,0,1

In [ ]:
#df_merged.to_csv("tm_cov_V2.csv", index=False)